-- 0054_up_docs_seed.sql — ÚP dokumenty pre 4 hlavné čadčianske k.ú. (z Mac up_monitor up_state.json).
-- Idempotentné (UNIQUE dataset_id,url). Vyplní ÚP sekciu v dossieri + /zoning pre Turzovka/Olešná/Raková/Čadca.
INSERT OR IGNORE INTO up_docs (dataset_id,title,url,kind,source_page) VALUES
('kn-800376','Schéma záväzných častí riešenia a verejnoprospešných stavieb','https://www.turzovka.sk/modules/file_storage/download.php?file=1f5a3fa5%7C172','schema','Turzovka'),
('kn-800376','Výkres ochrany prírody a tvorby krajiny','https://www.turzovka.sk/modules/file_storage/download.php?file=45e99a66%7C173','vykres','Turzovka'),
('kn-800376','Výkres budúceho možného použitia PP na stavebné a iné zámery','https://www.turzovka.sk/modules/file_storage/download.php?file=8cd03208%7C174','vykres','Turzovka'),
('kn-800376','Výkres riešenia verejného tech. vybavenia - energie, telekomunikácie','https://www.turzovka.sk/modules/file_storage/download.php?file=52beeb10%7C175','vykres','Turzovka'),
('kn-800376','Výkres riešenia verejného tech. vybavenia - vodné hospodárstvo','https://www.turzovka.sk/modules/file_storage/download.php?file=6d6ce021%7C176','vykres','Turzovka'),
('kn-800376','Výkres riešenia verejného dopravného vybavenia','https://www.turzovka.sk/modules/file_storage/download.php?file=5138a6ae%7C177','vykres','Turzovka'),
('kn-800376','Komplexný výkres priestor. usporiadania a funkč. využívania územia 2','https://www.turzovka.sk/modules/file_storage/download.php?file=ce3472f7%7C178','vykres','Turzovka'),
('kn-800376','Komplexný výkres priestor. usporiadania a funkč. využívania územia','https://www.turzovka.sk/modules/file_storage/download.php?file=d99d573f%7C179','vykres','Turzovka'),
('kn-800376','Výkres širších vzťahov','https://www.turzovka.sk/modules/file_storage/download.php?file=15458712%7C180','vykres','Turzovka'),
('kn-800376','Územný plán mesta Turzovka - textová časť','https://www.turzovka.sk/modules/file_storage/download.php?file=2460b652%7C181','text','Turzovka'),
('kn-800376','Vyhodnotenie komunitného plánu 2022 - 2023.pdf','https://www.turzovka.sk/e_download.php?file=data/editor/719sk_1.pdf&amp;original=Vyhodnotenie%20komunitn%C3%A9ho%20pl%C3%A1nu%202022%20-%202023.pdf','ine','Turzovka'),
('kn-800376','MK Turzovka Hlinné','https://www.turzovka.sk/modules/file_storage/download.php?file=9be38b09%7C908','ine','Turzovka'),
('kn-800376','MK Turzovka Turkov','https://www.turzovka.sk/modules/file_storage/download.php?file=926ab3dd%7C909','ine','Turzovka'),
('kn-800376','MK Turzovka Stred','https://www.turzovka.sk/modules/file_storage/download.php?file=a49bf3b9%7C910','ine','Turzovka'),
('kn-800376','MK Turzovka V. koniec + Závodie','https://www.turzovka.sk/modules/file_storage/download.php?file=0ec88a57%7C911','ine','Turzovka'),
('kn-800376','MK Turzovka Predmier','https://www.turzovka.sk/modules/file_storage/download.php?file=e045c817%7C912','ine','Turzovka'),
('kn-800376','MK 2013 - plán obnovy a údržby ciest','https://www.turzovka.sk/modules/file_storage/download.php?file=c95eaca8%7C913','ine','Turzovka'),
('kn-800376','Návrh Zadania pre Územný plán Zóny Turzovka - IBV Bukovina','https://www.turzovka.sk/modules/file_storage/download.php?file=413a8d09%7C135','ine','Turzovka'),
('kn-800376','Oznámenie o prerokovaní Návrhu Územného plánu zóny Turzovka - IBV Bukovina','https://www.turzovka.sk/modules/file_storage/download.php?file=dc3d0b39%7C136','ine','Turzovka'),
('kn-800376','VEREJNÁ VYHLÁŠKA','https://www.turzovka.sk/modules/file_storage/download.php?file=05d1fa09%7C137','ine','Turzovka'),
('kn-800376','Shéma zaväzných častí riešenia a verejnoprospešných stavieb','https://www.turzovka.sk/modules/file_storage/download.php?file=052b0f8b%7C138','ine','Turzovka'),
('kn-800376','Výkres širších vzťahov','https://www.turzovka.sk/modules/file_storage/download.php?file=f5fe88d0%7C139','vykres','Turzovka'),
('kn-800376','Výkres komplexného urbanistického návrhu riešeného územia','https://www.turzovka.sk/modules/file_storage/download.php?file=1a875a55%7C140','vykres','Turzovka'),
('kn-800376','Výkres verejného dopravného vybavenia s vyznačením vstupov na pozemok','https://www.turzovka.sk/modules/file_storage/download.php?file=7817e57f%7C141','vykres','Turzovka'),
('kn-800376','Výkres verejného technického vybavenia','https://www.turzovka.sk/modules/file_storage/download.php?file=3928ed9b%7C142','vykres','Turzovka'),
('kn-800376','Hlavný výkres priestorovej a funkčnej regulácie s vymedzením regulovaných priestorov','https://www.turzovka.sk/modules/file_storage/download.php?file=6dd8658d%7C143','vykres','Turzovka'),
('kn-800376','Územný plán zóny Turzovka IBV Bukovina - textová časť','https://www.turzovka.sk/modules/file_storage/download.php?file=3d9cc4d3%7C144','text','Turzovka'),
('kn-800376','Oznámenie o prerokúvaní Zmeny a Doplnku č.2 Územného plánu mesta Turzovka /orgánom ŠS,samosprávy, PO','https://www.turzovka.sk/modules/file_storage/download.php?file=c0ebcc8c%7C147','ine','Turzovka'),
('kn-800376','Oznámenie o prerokúvaní Zmeny a Doplnku č.2 Územného plánu mesta Turzovka /občanom, FO, PO','https://www.turzovka.sk/modules/file_storage/download.php?file=d2ccb9ec%7C148','ine','Turzovka'),
('kn-800376','Schéma záväzných častí riešenia a verejnoprospešných stavieb ZaD č. 2 Územného plánu mesta Turzovka','https://www.turzovka.sk/modules/file_storage/download.php?file=a59ae58d%7C149','schema','Turzovka'),
('kn-800376','Výkreš širších vzťahov ZaD č. 2 Územného plánu mesta Turzovka','https://www.turzovka.sk/modules/file_storage/download.php?file=601c13ac%7C150','ine','Turzovka'),
('kn-800376','Výkres priestorového usporiadania a funkčného využívania územia ZaD č. 2','https://www.turzovka.sk/modules/file_storage/download.php?file=db14d23c%7C151','vykres','Turzovka'),
('kn-800376','Komplexný výkres priestorového usporiadania a funkč. využívania ZaD č. 2','https://www.turzovka.sk/modules/file_storage/download.php?file=06f26c32%7C152','vykres','Turzovka'),
('kn-800376','Výkres riešenia verejného dopravného vybavenia ZaD č. 2','https://www.turzovka.sk/modules/file_storage/download.php?file=113c9416%7C153','vykres','Turzovka'),
('kn-800376','Výkres riešenia verejného technického vybavenia - vodné hospodárstvo ZaD č. 2','https://www.turzovka.sk/modules/file_storage/download.php?file=43aab42c%7C154','vykres','Turzovka'),
('kn-800376','Výkres riešenia verejného technického vybavenia - energie, telekomunikácie ZaD č. 2','https://www.turzovka.sk/modules/file_storage/download.php?file=3402a7f9%7C155','vykres','Turzovka'),
('kn-800376','Výkres budúceho možného použitia poľnohos. pôdy na stavebné a iné zámery ZaD č. 2','https://www.turzovka.sk/modules/file_storage/download.php?file=1b0d6a22%7C156','vykres','Turzovka'),
('kn-800376','Komunitný plán mesta Turzovka na roky 2018 - 2022','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_5.pdf&amp;original=2018_komunitny_plan_2018_2022.pdf','ine','Turzovka'),
('kn-800376','Vyhodnotenie pripomienok k návrhu zverejneného a predloženého Komunitného plánu sociálnych služieb mesta Turzovka na roky 2018 - 2022','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_6.pdf&amp;original=Vyhodnotenie%20pripomienok.pdf','ine','Turzovka'),
('kn-800376','schválený Komunitný plán sociálnych služieb mesta Turzovka na roky 2018 – 2022','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_7.pdf&amp;original=KPSS%20Turzovka%202018-2022%20VUC.pdf','ine','Turzovka'),
('kn-800376','Uznesenia riadiacej skupiny','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_1.pdf&amp;original=uznesenia_riadiacej_skupiny.pdf','ine','Turzovka'),
('kn-800376','Organizačný poriadok','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_2.pdf&amp;original=organizacny_poriadok.pdf','ine','Turzovka'),
('kn-800376','Rokovací poriadok','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_3.pdf&amp;original=rokovaci_poriadok_pracovnej_skupiny.pdf','ine','Turzovka'),
('kn-800376','Dotazník v PDF forme','https://www.turzovka.sk/e_download.php?file=data/editor/102sk_4.pdf&amp;original=dotaznik.pdf','ine','Turzovka'),
('kn-800376','Postup pre poskytovateľa sociálnej služby pri predkladaní žiadosti','https://www.turzovka.sk/e_download.php?file=data/editor/676sk_1.pdf&amp;original=Postup%20pre%20poskytovate%C4%BEa%20soci%C3%A1lnej%20slu%C5%BEby%20pri%20predkladan%C3%AD%20%C5%BEiadosti%20o%20p%C3%ADsomn%C3%A9%20vyjadrenie%20Mesta%20Turzovka.pdf','ine','Turzovka'),
('kn-800376','Kritéria pre zhodnotenie súladu poskytovateľa sociálnej služby','https://www.turzovka.sk/e_download.php?file=data/editor/676sk_2.pdf&amp;original=Krit%C3%A9ria%20pre%20zhodnotenie%20s%C3%BAladu%20poskytovate%C4%BEa%20soci%C3%A1lnej%20slu%C5%BEby%20s%20KPSS.pdf','ine','Turzovka'),
('kn-800376','Podklad k písomnému vyjadreniu pre žiadateľa','https://www.turzovka.sk/e_download.php?file=data/editor/676sk_3.pdf&amp;original=Podklad%20k%20p%C3%ADsomn%C3%A9mu%20vyjadreniu%20pre%20%C5%BEiadate%C4%BEa.pdf','ine','Turzovka'),
('kn-800376','KPSS Turzovka 2027-2032 dotazník','https://www.turzovka.sk/e_download.php?file=/data/editor/911sk_1.pdf&amp;original=KPSS%20Turzovka%202027-2032%20dotazn%C3%ADk.pdf','ine','Turzovka'),
('kn-800376','Žiadosť o územnoplánovaciu informáciu','https://www.turzovka.sk/e_download.php?file=data/editor/129sk_2.pdf&amp;original=%C5%BDiados%C5%A5%20o%20%C3%BAzemnopl%C3%A1novaciu%20inform%C3%A1ciu.pdf','ine','Turzovka'),
('kn-800376','Žiadosť o Zmenu UP','https://www.turzovka.sk/e_download.php?file=data/editor/783sk_2.pdf&amp;original=%C5%BDiados%C5%A5%20o%20Zmenu%20UP.pdf','ine','Turzovka'),
('kn-843610','Verejný oznam - územný plán','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/verejny-oznam-uzemny-plan.pdf','ine','Olešná'),
('kn-843610','Územný plán obce Olešná - úvodná strana','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-uvodna-strana.pdf','ine','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - sprievodná správa','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-sprievodna-sprava.pdf','text','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - obsah','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-obsah.pdf','ine','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - výkres širších vzťahov','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/vykres-sirsich-vztahov.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh A','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-a.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh B','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-b.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh C','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-c.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh D','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-d.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh E','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-e.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh F','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-f.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh G','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-g.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh H','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-h.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh I','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-i.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh J','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-j.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh K','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-k.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh L','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-l.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh M','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-m.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh N','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-n.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh O','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-o.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh P','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-p.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - komplexný návrh legenda','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/komplexny-navrh-legenda.pdf','vykres','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - doprava','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-doprava.pdf','ine','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - PPF','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-ppf.pdf','ine','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - TI','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-ti.pdf','ine','Olešná'),
('kn-843610','Územný plán obce Olešná - návrh - príroda','https://www.obecolesna.sk/images/stories/2022/pdf/uzemny-plan/uzemny-plan-priroda.pdf','ine','Olešná'),
('kn-843610','Vyhlásenie volieb do orgánov samosprávy obcí a samosprávnych krajov183.75 KB','https://www.obecolesna.sk/images/stories/2026/pdf/vyhlasenie_volieb_do_organov_samospravy_obci_a_samospravnych_krajov.pdf','ine','Olešná'),
('kn-843610','Informácia o podmienkach práva voliť a práva byť volený - voľby do orgánov samosprávy obcí201.62 KB','https://www.obecolesna.sk/images/stories/2026/pdf/Informacia_o_podmienkach_prava_volit_a_prava_byt_voleny_-_volby_do_organov_samospravy_obci.pdf','ine','Olešná'),
('kn-843610','Informácia o podmienkach práva voliť a práva byť volený do orgánov samosprávnych krajov201.29 KB','https://www.obecolesna.sk/images/stories/2026/pdf/Informacia_o_podmienkach_prava_volit_a_prava_byt_voleny_do_organov_samos_krajov.pdf','ine','Olešná'),
('kn-843610','Oznámenie_o_utvorení_volebného_obvodu_a_počet_poslancpv.pdf182.12 KB08/07/2026, 11:03','https://www.obecolesna.sk/images/stories/2026/Ozn%C3%A1menie_o_utvoren%C3%AD_volebn%C3%A9ho_obvodu_a_po%C4%8Det_poslancpv.pdf','ine','Olešná'),
('kn-843610','Oznámenie o utvorení volebných okrskov232.09 KB','https://www.obecolesna.sk/images/stories/2026/pdf/oznamenie-o-utvoreni-volebnych-okrskov.pdf','ine','Olešná'),
('kn-843610','Oznámenie o volebných obvodoch, o počte poslancov do orgánov ŽSK900.72 KB','https://www.obecolesna.sk/images/stories/2026/pdf/oznamenie-o-volebnych-obvodoch-o-pocte-poslancov-do-organov-%C5%BDSK.pdf','ine','Olešná'),
('kn-843610','Vymenovanie zapisovateľa miestnej volebnej komisie255.9 KB','https://www.obecolesna.sk/images/stories/2026/pdf/vymenovanie-zapisovatela-miestnej-volebnej-komisie.pdf','ine','Olešná'),
('kn-843610','Zoznam miest a obcí podľa jednotlivých volebných obvodov ŽSK2.02 MB','https://www.obecolesna.sk/images/stories/2026/pdf/zoznam-miest-a-obci-podla-jednotlivych-volebnych-obvodov-%C5%BDSK.pdf','ine','Olešná'),
('kn-843610','zverejnenie_emailovej_adresy.pdffalse','https://www.obecolesna.sk/images/stories/2026/zverejnenie_emailovej_adresy.pdf','ine','Olešná'),
('kn-843610','Informácie k voľbám – vzory tlačív152.14 KB','https://www.obecolesna.sk/images/stories/2026/pdf/informacie-k-volbam-vzory-tlaciv.pdf','ine','Olešná'),
('kn-843610','Oznámenie o určení počtu obyvateľov79.94 KB','https://www.obecolesna.sk/images/stories/2026/pdf/oznamenie-o-pocte-obyvatelov.pdf','ine','Olešná'),
('kn-843610','16-GDPR_-_Splnenie_informačnej_povinnosti_-_VOĽBY-2026_-_Obec_Olešná.pdffalse','https://www.obecolesna.sk/images/stories/2026/16-GDPR_-_Splnenie_informa%C4%8Dnej_povinnosti_-_VO%C4%BDBY-2026_-_Obec_Ole%C5%A1n%C3%A1.pdf','ine','Olešná'),
('kn-851388','Rozhodnutie č. 145 o vyhlásení volieb','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Rozhodnutie_%C4%8D._145_o_vyhl%C3%A1sen%C3%AD_volieb.pdf','ine','Raková'),
('kn-851388','Informácia o podmienkach práva voliť a práva byť volený - orgány samosprávy obcí','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Inform%C3%A1cia_o_podmienkach_pr%C3%A1va_voli%C5%A5_a_pr%C3%A1va_by%C5%A5_volen%C3%BD_-_OSO.pdf','ine','Raková'),
('kn-851388','Informácia o podmienkach práva voliť a práva byť volený - orgány samosprávnych krajov','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Inform%C3%A1cia_o_podmienkach_pr%C3%A1va_voli%C5%A5_a_pr%C3%A1va_by%C5%A5_volen%C3%BD_-_OSK.pdf','ine','Raková'),
('kn-851388','ŽSK - Oznámenie o volebných obvodoch, o počte poslancov, aký sa v nich má voliť, o sídle Volebnej komisie Žilinského samosprávneho kraja a o sídlach obvodných volebných komisií pre voľby do orgánov Ži','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/%C5%BDSK_OZN%C3%81MENIE_o_VO_o_po%C4%8Dte_poslancov_a_s%C3%ADdlach_VK_2026-2030.pdf','ine','Raková'),
('kn-851388','ŽSK - Zoznam miest a obcí podľa jednotlivých volebných obvodov Žilinského samosprávneho kraja','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/%C5%BDSK_Zoznam_miest_a_obc%C3%AD_patriacich_do_jednotliv%C3%BDch_VO_2026-2030.pdf','ine','Raková'),
('kn-851388','Oznámenie o utvorení volebných obvodov a o určení počtu poslancov pre voľby do orgánov samosprávy obcí 24. októbra 2026','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Ozn%C3%A1menie_o_utvoren%C3%AD_volebn%C3%BDch_obvodov_a_o_ur%C4%8Den%C3%AD_po%C4%8Dtu_poslancov_pre_vo%C4%BEby_do_org%C3%A1nov_samospr%C3%A1vy_obc%C3%AD_24._okt%C3%B3bra_2026.pdf','ine','Raková'),
('kn-851388','Utvorenie volebných okrskov a určenie volebných miestností','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Utvorenie_volebn%C3%BDch_okrskov_a_ur%C4%8Denie_volebn%C3%BDch_miestnost%C3%AD.pdf','ine','Raková'),
('kn-851388','Vymenovanie zapisovatela miestnej volebnej komisie','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Vymenovanie_zapisovatela_miestnej_volebnej_komisie.pdf','ine','Raková'),
('kn-851388','Oznámenie o počte obyvateľov - Obec Raková','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Oznamenie_o_pocte_obyvatelov_-_Obec_Rakov%C3%A1.pdf','ine','Raková'),
('kn-851388','Oznámenie o rozsahu výkonu funkcie starostu - Obec Raková','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Oznamenie_o_rozsahu_vykonu_funkcie_starostu__Obec_Rakov%C3%A1.pdf','ine','Raková'),
('kn-851388','Emailová adresa na doručenie oznámení - Obec Raková','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Emailov%C3%A1_adresa_na_doru%C4%8Denie_ozn%C3%A1men%C3%AD_-_Obec_Rakov%C3%A1.pdf','ine','Raková'),
('kn-851388','Zapisovatel miestna volebná komisia - odvolanie dňom 24.08.2026','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Zapisovatel_miestna_volebn%C3%A1_komisia_-_odvolanie_d%C5%88om_24.08.2026.pdf','ine','Raková'),
('kn-851388','Zapisovatel miestna volebná komisia - vymenovanie dňom 24.08.2026','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Zapisovatel_miestna_volebn%C3%A1_komisia_-_vymenovanie_d%C5%88om_24.08.2026.pdf','ine','Raková'),
('kn-851388','Predkladanie kandidátnych listín','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Predkladanie_kandid%C3%A1tnych_list%C3%ADn.pdf','ine','Raková'),
('kn-851388','Zapisovateľ miestna volebná komisia - odvolanie dňom 31.08.2026','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Zapisovatel_miestna_volebn%C3%A1_komisia_-_odvolanie_d%C5%88om_31.08.2026.pdf','ine','Raková'),
('kn-851388','Zapisovateľ miestna volebná komisia - vymenovanie dňom 31.08.2026','https://www.rakova.sk/images/stories/2026/%C3%9Aradn%C3%A9_oznamy/Zapisovatel_miestna_volebn%C3%A1_komisia_-_vymenovanie_d%C5%88om_31.08.2026.pdf','ine','Raková'),
('kn-808393','Územný plán - textová časť','https://www.mestocadca.sk/files/attachments/uzemny-plan-cadca-textova-cast.pdf','text','Čadca'),
('kn-808393','Záväzná časť','https://www.mestocadca.sk/files/attachments/uzemny-plan-zavazna-cast.pdf','text','Čadca'),
('kn-808393','Výkres širších vzťahov','https://www.mestocadca.sk/files/uzemny-plan/vykres-sirsich-vztahov.pdf','vykres','Čadca'),
('kn-808393','Komplexný výkres priestorového usporiadania a funkčné využívanie územia','https://www.mestocadca.sk/files/uzemny-plan/komplexny-vykres-priestoroveho-usporiadania-a-funkcneho-vyuzivania-uzemia.pdf','vykres','Čadca'),
('kn-808393','Záväzné časti riešenia a verejnoprospešné stavby','https://www.mestocadca.sk/files/uzemny-plan/zavazne-casti-riesenia-a-verejnoprospesne-stavby.pdf','text','Čadca'),
('kn-808393','Výkres riešenia verejného dopravného vybavenia','https://www.mestocadca.sk/files/uzemny-plan/vykres-riesenia-verejneho-dopravneho-vybavenia.pdf','vykres','Čadca'),
('kn-808393','Výkres riešenia verejného technického vybavenia - vodné hospodárstvo','https://www.mestocadca.sk/files/uzemny-plan/vykres-riesenia-verejneho-technickeho-vybavenia-vodne-hospodarstvo.pdf','vykres','Čadca'),
('kn-808393','Výkres riešenia verejného technického vybavenia - el. energia, telekomunikácie','https://www.mestocadca.sk/files/uzemny-plan/vykres-riesenia-verejneho-technickeho-vybavenia-el-energia-telekomunikacie.pdf','vykres','Čadca'),
('kn-808393','Výkres riešenia verejného technického vybavenia - teplo, plyn','https://www.mestocadca.sk/files/uzemny-plan/vykres-riesenia-verejneho-technickeho-vybavenia-teplo-plyn.pdf','vykres','Čadca'),
('kn-808393','Vyhodnotenie budúceho možného použitia PP na stavebné a iné zámery','https://www.mestocadca.sk/files/uzemny-plan/vyhodnotenie-buduceho-mozneho-pouzitia-pp-na-stavebne-a-ine-zamery.pdf','ine','Čadca'),
('kn-808393','Výkres ochrany prírody a tvorby krajiny','https://www.mestocadca.sk/files/uzemny-plan/vykres-ochrany-prirody-a-tvorby-krajiny.pdf','vykres','Čadca'),
('kn-808393','Územný plán - textová časť','https://www.mestocadca.sk/files/up1/uzemny-plan-1-cadca-textova-cast.pdf','text','Čadca'),
('kn-808393','Výkres širších vzťahov','https://www.mestocadca.sk/files/up1/vykres-sirsich-vztahov.pdf','vykres','Čadca'),
('kn-808393','Komplexný výkres priestorového usporiadania a funkčné využívanie územia','https://www.mestocadca.sk/files/up1/komplexny-vykres-priestoroveho-usporiadania-a-funkcneho-vyuzivania-uzemia.pdf','vykres','Čadca'),
('kn-808393','Záväzné časti riešenia a verejnoprospešné stavby','https://www.mestocadca.sk/files/up1/zavazne-casti-riesenia-a-verejnoprospesne-stavby.pdf','text','Čadca');
INSERT OR IGNORE INTO up_docs (dataset_id,title,url,kind,source_page) VALUES
('kn-808393','Výkres riešenia verejného dopravného vybavenia','https://www.mestocadca.sk/files/up1/vykres-riesenia-verejneho-dopravneho-vybavenia.pdf','vykres','Čadca'),
('kn-808393','Výkres riešenia verejného technického vybavenia - vodné hospodárstvo','https://www.mestocadca.sk/files/up1/vykres-riesenia-verejneho-technickeho-vybavenia-vodne-hospodarstvo.pdf','vykres','Čadca'),
('kn-808393','Výkres riešenia verejného technického vybavenia - el. energia, telekomunikácie','https://www.mestocadca.sk/files/up1/vykres-riesenia-verejneho-technickeho-vybavenia-el-energia-telekomunikacie.pdf','vykres','Čadca'),
('kn-808393','Výkres riešenia verejného technického vybavenia - teplo, plyn','https://www.mestocadca.sk/files/up1/vykres-riesenia-verejneho-technickeho-vybavenia-teplo-plyn.pdf','vykres','Čadca'),
('kn-808393','Vyhodnotenie budúceho možného použitia PP na stavebné a iné zámery','https://www.mestocadca.sk/files/up1/vyhodnotenie-buduceho-mozneho-pouzitia-pp-na-stavebne-a-ine-zamery.pdf','ine','Čadca'),
('kn-808393','Výkres ochrany prírody a tvorby krajiny','https://www.mestocadca.sk/files/up1/vykres-ochrany-prirody-a-tvorby-krajiny.pdf','vykres','Čadca'),
('kn-808393','Komplexný výkres priestorového usporiadania a funkčné využívanie územia','https://www.mestocadca.sk/files/up2/komplexny-vykres-priestoroveho-usporiadania-a-funkcneho-vyuzivania-uzemia.pdf','vykres','Čadca'),
('kn-808393','Širšie vzťahy','https://www.mestocadca.sk/files/up3/1-uzemny-plan-sirsie-vzthay.pdf','ine','Čadca'),
('kn-808393','Priestorového usporiadania a funkčné využívanie územia','https://www.mestocadca.sk/files/up3/2-priestorove-usporiadanie-a-funkcne-vyuzivanie-uzemia.pdf','ine','Čadca'),
('kn-808393','Riešenia verejného dopravného vybavenia','https://www.mestocadca.sk/files/up3/3-verejne-dopravne-vybavenie.pdf','ine','Čadca'),
('kn-808393','Vodné hospodárstvo','https://www.mestocadca.sk/files/up3/4-vodne-hospodarstvo.pdf','ine','Čadca'),
('kn-808393','Energie, telekomunikácie','https://www.mestocadca.sk/files/up3/5-energie-telekomunikacie.pdf','ine','Čadca'),
('kn-808393','Teplo, plyn','https://www.mestocadca.sk/files/up3/6-teplo-plyn.pdf','ine','Čadca'),
('kn-808393','Vyhodnotenia dôsledkov navrhovaného stavebného rozvoja a iných zámerov na poľnohosp. a lesnej pôde','https://www.mestocadca.sk/files/up3/7-dosledky-stavebneho-rozvoja-a-inych-zamerov-na-polnoh-a-lesnej-pode.pdf','ine','Čadca'),
('kn-808393','Ochrana prírody a tvorba krajiny','https://www.mestocadca.sk/files/up3/8-ochrana-prirody-a-tvorba-krajiny.pdf','ine','Čadca'),
('kn-808393','Schéma','https://www.mestocadca.sk/files/up3/schema.pdf','schema','Čadca'),
('kn-808393','Územný plán - textová časť','https://www.mestocadca.sk/files/up3/uzemny-plan-textova-cast.pdf','text','Čadca'),
('kn-808393','Grafická časť (veľkosť 23.3 MB, formát zip)','https://www.mestocadca.sk/files/up4/up-cadca-doplnok-4-graficka-cast.zip','ine','Čadca'),
('kn-808393','Textová časť (veľkosť 253 KB, formát zip)','https://www.mestocadca.sk/files/up4/up-cadca-doplnok-c-4-textova-cast.zip','text','Čadca'),
('kn-808393','Grafická časť (veľkosť 33 MB, formát zip)','https://www.mestocadca.sk/files/up5/up-cadca-doplnok-c-5-graficka-cast.zip','ine','Čadca'),
('kn-808393','Textová časť (veľkosť 287 KB, formát zip)','https://www.mestocadca.sk/files/up5/up-cadca-doplnok-c-5-textova-cast.zip','text','Čadca'),
('kn-808393','Grafická časť (veľkosť 14.5 MB, formát zip)','https://www.mestocadca.sk/files/up6/up-cadca-doplnok-c-6-graficka-cast.zip','ine','Čadca'),
('kn-808393','Textová časť (veľkosť 271 KB, formát pdf)','https://www.mestocadca.sk/files/up6/up-cadca-doplnok-c-6-textova-cast.pdf','text','Čadca'),
('kn-808393','Harmonogram vývozov odpadov','https://www.mestocadca.sk/files/attachments/harmonogram-vyvozov-cadca-2019.pdf','ine','Čadca'),
('kn-808393','VZN ktorým sa vyhlasuje záväzná časť Zmeny a Doplnku č. 7 Územného plánu mesta Čadca 2/2026','https://www.mestocadca.sk/files/vzn-2-2026.pdf','text','Čadca'),
('kn-808393','VZN o prijímaní detí do materských škôl a na plnenie povinnej školskej dochádzky v základných školách v zriaďovateľskej pôsobnosti Mesta Čadca 1/2026','https://www.mestocadca.sk/files/vzn-1-2026.pdf','ine','Čadca'),
('kn-808393','VZN ktorým sa určujú podmienky predaja výrobkov a poskytovania služieb na trhových miestach v meste Čadca 1/2025','https://www.mestocadca.sk/files/vzn-1-2025.pdf','ine','Čadca'),
('kn-808393','VZN o miestnom poplatku za rozvoj 3/2024','https://www.mestocadca.sk/files/vzn-3-2024.pdf','ine','Čadca'),
('kn-808393','VZN ktorým sa zrušuje VZN č. 1/2022 o určení výšky dotácie na mzdy a prevádzku na dieťa materskej školy, žiaka základnej umeleckej školy, dieťa školského zariadenia v zriaďovateľskej pôsobnosti Mesta ','https://www.mestocadca.sk/files/vzn-2-2024.pdf','ine','Čadca'),
('kn-808393','VZN o podmienkach poskytovania dotácií z prostriedkov Mesta Čadca 1/2024','https://www.mestocadca.sk/files/vzn-1-2024.pdf','ine','Čadca'),
('kn-808393','VZN o miestnom poplatku za komunálne odpady a drobné stavebné odpady v znení dodatku č.1 10/2023','https://www.mestocadca.sk/files/vzn-10-2023.pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje v znení dodatku č.1 a č.2 9/2023','https://www.mestocadca.sk/files/vzn-9-2023.pdf','ine','Čadca'),
('kn-808393','VZN o poplatku za znečisťovanie ovzdušia malými zdrojmi znečisťovania ovzdušia na území mesta Čadca 8/2023','https://www.mestocadca.sk/files/vzn-8-2023-1.pdf','ine','Čadca'),
('kn-808393','VZN o určení názvu verejného priestranstva na „Alej Jozefa Hnitku“ 7/2023','https://www.mestocadca.sk/files/vzn-7-2023.pdf','ine','Čadca'),
('kn-808393','VZN o ochrane pamätihodností na území mesta, o podmienkach výberu pamätihodností mesta a ich zápise do Zoznamu pamätihodností mesta Čadca 6/2023','https://www.mestocadca.sk/files/vzn-6-2023.pdf','ine','Čadca'),
('kn-808393','VZN verejnom poriadku 5/2023','https://www.mestocadca.sk/files/vzn-5-2023.pdf','ine','Čadca'),
('kn-808393','VZN o zákaze predaja, podávania alebo požívania alkoholických nápojov na verejne prístupných miestach 4/2023','https://www.mestocadca.sk/files/vzn-4-2023.pdf','ine','Čadca'),
('kn-808393','VZN o poplatku za znečisťovanie ovzdušia malými zdrojmi znečisťovania ovzdušia na území mesta Čadca 3/2023 - zrušené','https://www.mestocadca.sk/files/vzn-3-2023.pdf','ine','Čadca'),
('kn-808393','VZN o nakladaní s komunálnymi odpadmi a drobnými stavebnými odpadmi na území mesta Čadca 2/2023','https://www.mestocadca.sk/files/vzn-2-2023.pdf','ine','Čadca'),
('kn-808393','VZN o výške príspevku na čiastočnú úhradu nákladov a podmienky úhrady v školskej jedálni na nákup potravín na jedno jedlo podľa vekových kategórií stravníkov v zariadeniach školského stravovania v zri','https://www.mestocadca.sk/files/vzn-1-2023.pdf','ine','Čadca'),
('kn-808393','VZN o miestnom poplatku za komunálne odpady a drobné stavebné odpady 4/2022 - platné','https://www.mestocadca.sk/files/vzn-4-2022.pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností dani za psa dani za ubytovanie dani za predajné automaty a dani za nevýherné hracie prístroje 3/2022 - platné a účinné','https://www.mestocadca.sk/files/vzn-3-2022.pdf','ine','Čadca'),
('kn-808393','VZN o dočasnom parkovaní motorových vozidiel na vymedzenom území mesta Čadca 2/2022','https://www.mestocadca.sk/files/vzn-2-2022.pdf','ine','Čadca'),
('kn-808393','VZN o určení výšky dotácie na mzdy a prevádzku na dieťa materskej školy, žiaka základnej umeleckej školy, dieťa školského zariadenia 1/2022','https://www.mestocadca.sk/files/vzn-1-2022.pdf','ine','Čadca'),
('kn-808393','VZN o ochrane drevín, ktoré sú súčasťou verejnej zelene na území mesta Čadca 6/2021','https://www.mestocadca.sk/files/vzn-6-2021.pdf','ine','Čadca'),
('kn-808393','VZN o určení spádových materských škôl v zriaďovateľskej pôsobnosti Mesta Čadca 5/2021','https://www.mestocadca.sk/files/vzn-5-2021.pdf','ine','Čadca'),
('kn-808393','VZN o prideľovaní nájomných bytov vo vlastníctve mesta Čadca, výške nájmu a o tvorbe a použití fondu prevádzky, údržby a opráv 4/2021','https://www.mestocadca.sk/files/vzn-4-2021.pdf','ine','Čadca'),
('kn-808393','VZN o výške príspevku na čiastočnú úhradu nákladov a podmienky úhrady v školskej jedálni na jedno jedlo podľa vekových kategórií stravníkov v zariadeniach školského stravovania v zriaďovateľskej pôsob','https://www.mestocadca.sk/files/vzn-3-2021.pdf','ine','Čadca'),
('kn-808393','VZN Prevádzkový poriadok pohrebiska Mesta Čadca 2/2021','https://www.mestocadca.sk/files/vzn-2-2021.pdf','ine','Čadca'),
('kn-808393','VZN o zrušení Výdajných školských jedální a zriadení Školskej jedálne a výdajných školských jedální pri Základných školách v zriaďovateľskej pôsobnosti Mesta Čadca 1/2021','https://www.mestocadca.sk/files/vzn-1-2021.pdf','ine','Čadca'),
('kn-808393','VZN o dani za vjazd a zotrvanie motorového vozidla v historickej časti mesta 6/2019','https://www.mestocadca.sk/files/vzn-6-2019.pdf','ine','Čadca'),
('kn-808393','VZN o dani za užívanie verejného priestranstva 5/2019','https://www.mestocadca.sk/files/vzn-5-2019.pdf','ine','Čadca'),
('kn-808393','VZN o miestnom poplatku za komunálne odpady a drobné stavebné odpady 4/2019','https://www.mestocadca.sk/files/vzn-4-2019.pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje 3/2019 - nesúlad so zákonom','https://www.mestocadca.sk/files/vzn-3-2019.pdf','ine','Čadca'),
('kn-808393','VZN ktorým sa určujú pravidlá času predaja v obchode a času prevádzky služieb na území Mesta Čadca 2/2019','https://www.mestocadca.sk/files/vzn-2-2019.pdf','ine','Čadca'),
('kn-808393','VZN o verejnom poriadku 1/2019','https://www.mestocadca.sk/files/vzn-1-2019.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti zmien a doplnkov č. 6 územného plánu mesta Čadca','https://www.mestocadca.sk/files/VZN o záväznej časti zmien a doplnkov č. 6 územného plánu mesta Čadca.pdf','ine','Čadca'),
('kn-808393','VZN o nakladaní skomunálnymi odpadmi a s drobnými stavebnými odpadmi na území mesta Čadca 2/2018 - zrušené','https://www.mestocadca.sk/files/vzn-2-2018.pdf','ine','Čadca'),
('kn-808393','VZN o poskytovaní sociálnych služieb, spôsobe ich určenia a výške úhrady 1/2018','https://www.mestocadca.sk/files/vzn-1-2018.pdf','ine','Čadca'),
('kn-808393','VZN o poplatkoch za znečisťovanie ovzdušia na území mesta Čadca prevádzkovateľmi malých zdrojov znečistenia ovzdušia 3/2017 - zrušené','https://www.mestocadca.sk/files/vzn-3-2017.pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje 2/2017 - zrušená účinnosť','https://www.mestocadca.sk/files/vzn-2-2017.pdf','ine','Čadca'),
('kn-808393','VZN o podmienkach poskytovania dotácií z prostriedkov Mesta Čadca 1/2017','https://www.mestocadca.sk/files/vzn-1-2017.pdf','ine','Čadca'),
('kn-808393','VZN o miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vznikli na území mesta Čadca 7/2016 - zrušená účinnosť','https://www.mestocadca.sk/files/vzn-7-2016.pdf','ine','Čadca'),
('kn-808393','VZN o podmienkach vylepovania plagátov na verejných priestranstvách a vo vitrínach 6/2016','https://www.mestocadca.sk/files/vzn-6-2016.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku č. 5 Územného plánu mesta Čadca 5/2016','https://www.mestocadca.sk/files/vzn-5-2016.pdf','text','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje 4/2016 - zrušená účinnosť','https://www.mestocadca.sk/files/vzn-4-2016.pdf','ine','Čadca'),
('kn-808393','VZN o vyhradení miest na umiestňovanie volebných plagátov počas volebnej kampane 3/2016','https://www.mestocadca.sk/files/vzn-3-2016.pdf','ine','Čadca'),
('kn-808393','VZN o poskytovaní jednorazovej dávky v hmotnej núdzi a mimoriadnej pomoci občanovi č. 2/2016','https://www.mestocadca.sk/files/vzn-2-2016.pdf','ine','Čadca'),
('kn-808393','VZN o nakladaní s komunálnymi odpadmi a drobnými stavebnými odpadmi na území mesta čadca 1/2016 - zrušené','https://www.mestocadca.sk/files/vzn-1-2016.pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje 5/2015','https://www.mestocadca.sk/files/vzn-5-2015.pdf','ine','Čadca'),
('kn-808393','VZN o miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vznikli na území mesta Čadca 4/2015 - zrušené','https://www.mestocadca.sk/files/vzn-4-2015(1).pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje na kalendárny rok 2016 3/2015 - zrušená účinnosť','https://www.mestocadca.sk/files/vzn-3-2015.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti zmeny a doplnku 2014 územného plánu centrálnej mestskej zóny Čadca 2/2015','https://www.mestocadca.sk/files/vzn-2-2015.pdf','text','Čadca'),
('kn-808393','VZN o určení výšky dotácie na prevádzku a mzdy na dieťa/ žiaka škôl a školských zariadení na území mesta Čadca a na dieťa/žiaka CVČ zriaďovateľov v iných obciach 1/2015','https://www.mestocadca.sk/files/vzn-1-2015.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti zmeny a doplnku 2013 územného plánu centrálnej mestskej zóny Čadca 3/2014','https://www.mestocadca.sk/files/vzn-3-2014.pdf','text','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku č. 5 Územného plánu mesta Čadca 5/2016','https://www.mestocadca.sk/files/vzn-5-2016-1.pdf','text','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku 2014 Územného plánu centrálnej mestskej zóny Čadca 2/2015','https://www.mestocadca.sk/files/vzn-2-2015-1.pdf','text','Čadca'),
('kn-808393','VZN o miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vznikli na území mesta Čadca 6/2014 - zrušené','https://www.mestocadca.sk/files/vzn-6-2014.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku č. 4 Územného plánu mesta Čadca 1/2014','https://www.mestocadca.sk/files/vzn-1-2014.pdf','text','Čadca'),
('kn-808393','VZN O miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vznikli na území mesta Čadca 145/2013 - zrušené','https://www.mestocadca.sk/files/vzn-145-2013.pdf','ine','Čadca'),
('kn-808393','VZN o nakladaní s komunálnymi odpadmi a s drobnými stavebnými odpadmi vrátane biologicky rozložiteľných kuchynských a reštauračných odpadov od prevádzkovateľa kuchyne a elektroodpadov z domácnosti na ','https://www.mestocadca.sk/files/vzn-144-2013.pdf','ine','Čadca'),
('kn-808393','VZN o dani z nehnuteľností, dani za psa, dani za ubytovanie, dani za predajné automaty a dani za nevýherné hracie prístroje 143/2013 - zrušené','https://www.mestocadca.sk/files/vzn-143-2013.pdf','ine','Čadca'),
('kn-808393','VZN o dočasnom parkovaní motorových vozidiel na miestnych komunikáciách v meste Čadca 142/2013.','https://www.mestocadca.sk/files/vzn-142-2013.pdf','ine','Čadca'),
('kn-808393','VZN O podnikateľskej činnosti a určení času predaja v obchode a času prevádzky sluţieb na území mesta Čadca 141/2013','https://www.mestocadca.sk/files/vzn-141-2013.pdf','ine','Čadca'),
('kn-808393','VZN o Trhovom poriadku Trhoviska II na parc. č. 1275/11,vlastník Peter Tomek TODAKO, Palárikova 176, Čadca 140/2013','https://www.mestocadca.sk/files/vzn-140-2013.pdf','ine','Čadca'),
('kn-808393','VZN o podmienkach predaja výrobkov a poskytovania služieb na trhových miestach 139/2013','https://www.mestocadca.sk/files/vzn-139-2013.pdf','ine','Čadca'),
('kn-808393','VZN o organizovaní verejných kultúrnych podujatí na území mesta Čadca 138/2013','https://www.mestocadca.sk/files/vzn-138-2013.pdf','ine','Čadca'),
('kn-808393','VZN o prevádzkovaní taxislužby na území mesta Čadca 137/2013','https://www.mestocadca.sk/files/vzn-137-2013.pdf','ine','Čadca'),
('kn-808393','VZN O miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vznikli na území mesta Čadca 135/2012','https://www.mestocadca.sk/files/vzn-135-2012.pdf','ine','Čadca'),
('kn-808393','VZN O nakladaní s komunálnymi odpadmi a s drobnými stavebnými odpadmi, vrátane biologicky rozloţiteľných kuchynských a reštauračných odpadov od prevádzkovateľa kuchyne a elektroodpadov z domácností 13','https://www.mestocadca.sk/files/vzn-134-2012.pdf','ine','Čadca'),
('kn-808393','VZN O podmienkach držania psov na území mesta Čadca 133/2012 - zrušené','https://www.mestocadca.sk/files/vzn-133-2012.pdf','ine','Čadca'),
('kn-808393','VZN O spôsobe určenia úhrady, výšky úhrady a spôsobe platenia úhrady za opatrovateľskú službu 132/2012','https://www.mestocadca.sk/files/vzn-132-2012.pdf','ine','Čadca'),
('kn-808393','VZN O miestnych daniach 131/2012 - zrušené','https://www.mestocadca.sk/files/vzn-131-2012.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku č. 3 Územného plánu mesta Čadca 130/2012','https://www.mestocadca.sk/files/vzn-130-2012.pdf','text','Čadca'),
('kn-808393','VZN O nakladaní s komunálnymi odpadmi a s drobnými stavebnými odpadmi a elektroodpadmi z domácností, ktoré vznikli na území mesta Čadca 129/2012 - zrušené','https://www.mestocadca.sk/files/vzn-129-2012.pdf','ine','Čadca'),
('kn-808393','VZN o povinnosti vypracovať povodňové plány záchranných prác právnických a fyzických osôb – podnikateľov na území mesta 127/2012','https://www.mestocadca.sk/files/vzn-povodnove-plany-127-2012.pdf','ine','Čadca'),
('kn-808393','O miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vnznikli na území mesta 126/2011 - zrušené','https://www.mestocadca.sk/files/vzn-126-2011.pdf','ine','Čadca'),
('kn-808393','VZN O nakladaní s komunálnymi odpadmi a s drobnými stavebnými odpadmi a elektroodpadmi z domácností, ktoré vznikli na území mesta Čadca 125/2011 - zrušené','https://www.mestocadca.sk/files/vzn-125-2011.pdf','ine','Čadca'),
('kn-808393','VZN o podmienkach umiestňovania, povoľovania a prevádzkovania sezónnych vonkajších obslužných zariadení na území Mesta Čadca 124/2011','https://www.mestocadca.sk/files/vzn-124-2011.pdf','ine','Čadca'),
('kn-808393','VZN o zabezpečení dodávky vody z verejného vodovodu a odvádzaní odpadovej vody verejnou kanalizáciou v katastrálnom území mesta Čadca a Horelica v mieste, kde je verejný vodovod a verejná kanalizácia ','https://www.mestocadca.sk/files/vzn-123-2011.pdf','ine','Čadca'),
('kn-808393','VZN o výške mesačného príspevku na čiastočnú úhradu nákladov na činnosti školských klubov deti 122/2011','https://www.mestocadca.sk/files/vzn-122-2011.pdf','ine','Čadca'),
('kn-808393','VZN upravujúce zásady hospodárenia a nakladania s majetkom Mesta Čadca 120/2011','https://www.mestocadca.sk/files/vzn-120-2011.pdf','ine','Čadca'),
('kn-808393','VZN o výške príspevku na čiastočnú úhradu nákladov a podmienky úhrady v školskej jedálni na jedno jedlo podľa vekových kategórií stravníkov v zariadeniach školského stravovania 118/2011','https://www.mestocadca.sk/files/vzn-118-2011.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku 2013 Územného plánu centrálnej mestskej zóny Čadca 3/2014','https://www.mestocadca.sk/files/vzn-3-2014-1.pdf','text','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku č. 4 Územného plánu mesta Čadca 1/2014','https://www.mestocadca.sk/files/vzn-1-2014-1.pdf','text','Čadca'),
('kn-808393','VZN o podmienkach predaja výrobkov a poskytovania služieb na trhových miestach v Meste Čadca 116/2011','https://www.mestocadca.sk/files/vzn-116-2010.pdf','ine','Čadca'),
('kn-808393','VZN ktorým sa schvaľuje Prevádzkový poriadok pohrebiska – Cintorínsky poriadok v meste Čadca 115/2010','https://www.mestocadca.sk/files/vzn-115-2010.pdf','ine','Čadca'),
('kn-808393','VZN o podmienkach držania psov na území mesta Čadca 113/2010 - zrušené','https://www.mestocadca.sk/files/vzn-o-podmienkach-drzania-psov-na-uzemi-mesta-cadca.pdf','ine','Čadca'),
('kn-808393','VZN o poplatkoch za znečisťovanie ovzdušia prevádzkovateľmi malých zdrojov znečistenia ovzdušia na území mesta Čadca 112/2010 - zrušené','https://www.mestocadca.sk/files/vzn-o-poplatkoch-za-znecistovanie-ovzdusia112-2010.pdf','ine','Čadca'),
('kn-808393','O dani za nevýherné hracie prístroje 111/2010 - zrušená účinnosť','https://www.mestocadca.sk/files/VZN-o-dani-za-nevyherne-hracie-pristroje-111-2010.pdf','ine','Čadca'),
('kn-808393','O dani za predajné automaty 110/2010 - zrušená účinnosť','https://www.mestocadca.sk/files/VZN-o-dani-za-predajne-automaty-110-2010.pdf','ine','Čadca'),
('kn-808393','Daň za ubytovanie 109/2010 - zrušená účinnosť','https://www.mestocadca.sk/files/VZN-dan-za-ubytovanie-109-2010.pdf','ine','Čadca'),
('kn-808393','Daň za psa 108/2010 - zrušená účinnosť','https://www.mestocadca.sk/files/VZN-dan-za-psa-108-2010.pdf','ine','Čadca'),
('kn-808393','Daň z nehnuteľností 107/2010 - zrušená účinnosť','https://www.mestocadca.sk/files/VZN-dan-z-nehnutelnosti-107-2010.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku Územného plánu centrálnej mestskej zóny Čadca – Ulica 17. novembra 105/2010','https://www.mestocadca.sk/files/vzn-105-2010.pdf','text','Čadca'),
('kn-808393','VZN o určení výšky dotácie na prevádzku a mzdy na žiaka škôl a školských zariadení na území mesta Čadca 104/2009','https://www.mestocadca.sk/files/vzn-o-urceni-vysky-dotacie-na-prevadzku-a-mzdy-ziaka104-2009.pdf','ine','Čadca'),
('kn-808393','O parkovaní a státí motorových vozidiel na miestnych komunikáciách a verejných priestranstvách v meste Čadca 103/2009','https://www.mestocadca.sk/files/vzn-103-2009.pdf','ine','Čadca'),
('kn-808393','O dani za vjazd a zotrvanie motorového vozidla v historickej časti mesta Čadca 102/2009','https://www.mestocadca.sk/files/VZN-o-dan-za-vjazd-a-zotrvanie-motoroveho-vozidla-v-historickej-casti-mesta-102-2009.pdf','ine','Čadca'),
('kn-808393','O poskytovaní dotácií z rozpočtu mesta 101/2009','https://www.mestocadca.sk/files/VZN-o-poskytovani-dotacii-z-rozpoctu-mesta-Cadca-2010.pdf','ine','Čadca'),
('kn-808393','O miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vnznikli na území mesta 100/2009 - zrušené','https://www.mestocadca.sk/files/VZN-o-miestnom-poplatku-za-komunalne-odpady-a-drobne-stavebne-odpady-2009.pdf','ine','Čadca');
INSERT OR IGNORE INTO up_docs (dataset_id,title,url,kind,source_page) VALUES
('kn-808393','O nakladaní s komunálnimi odpadmi a s drobnými stavebnými odpadmi a elektroodpadmi z domácností, ktoré vznikli na území mesta Čadca 99/2009 - zrušené','https://www.mestocadca.sk/files/VZN-o-nakladani-s-komunalnymi-a-drobnymi-stavebnymi-odpadmi-a-elektroodpadmi-2009.pdf','ine','Čadca'),
('kn-808393','O dani za nevýherné hracie prístroje na kalendárny rok 2010 97/2009','https://www.mestocadca.sk/files/VZN-o-dani-za-nevyherne-hracie-pristroje-2010-Cadca.pdf','ine','Čadca'),
('kn-808393','O dani za predajné automaty na kalendárny rok 2010 96/2009','https://www.mestocadca.sk/files/VZN-o-dani-za-predajne-automaty-Cadca-2010.pdf','ine','Čadca'),
('kn-808393','O dani za ubytovanie na kalendárny rok 2010 95/2009','https://www.mestocadca.sk/files/VZN-o-dani-za-ubytovanie-2010-Cadca.pdf','ine','Čadca'),
('kn-808393','O dani za psa na kalendárny rok 2010 94/2009','https://www.mestocadca.sk/files/VZN-o-dani-za-psa-2010-Cadca.pdf','ine','Čadca'),
('kn-808393','O dani z nehnuteľnosti na kalendárny rok 2010 93/2009','https://www.mestocadca.sk/files/VZN-o-dani-z-nehnutelnosti-2010-Cadca.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Zmeny a Doplnku č. 2 Územného plánu mesta Čadca 92/2009','https://www.mestocadca.sk/files/vzn-92-2009.pdf','text','Čadca'),
('kn-808393','O poplatkoch za znečisťovanie ovzdušia prevádzkovateľmi malých zdrojov znečistenia ovzdušia na území mesta Čadca 90/2008 - zrušené','https://www.mestocadca.sk/files/VZN_popl_MZZO.pdf','ine','Čadca'),
('kn-808393','O miestnom poplatku za komunálne odpady a drobné stavebné odpady, ktoré vznikli na území mesta 89/2008 - zrušené','https://www.mestocadca.sk/files/VZN_poplatky_2009.pdf','ine','Čadca'),
('kn-808393','O spôsobe určenia úhrady, výšky úhrady a spôsobe platenia úhrady za opatrovateľskú službu 88/2008','https://www.mestocadca.sk/files/VZN-opatrovatelska-sluzba-uhrady.pdf','ine','Čadca'),
('kn-808393','O nakladaní s komunálnymi odpadmi a s drobnými stavebnými odpadmi a elektroodpadmi z domácností, ktoré vznikli na území mesta Čadca 87/2008 - zrušené','https://www.mestocadca.sk/files/VZN_zvoz_KO_2009.pdf','ine','Čadca'),
('kn-808393','O dani za nevýherné hracie prístroje 86/2008','https://www.mestocadca.sk/files/VZN_nevyhrene_hracie_pristroje_2009.pdf','ine','Čadca'),
('kn-808393','O dani za predajné automaty 85/2008','https://www.mestocadca.sk/files/VZN_o_dani_za_predajne_automaty_2009.pdf','ine','Čadca'),
('kn-808393','O dani za ubytovanie 84/2008','https://www.mestocadca.sk/files/VZN_o_dani_za_ubytovanie_2009.pdf','ine','Čadca'),
('kn-808393','O dani za psa 83/2008','https://www.mestocadca.sk/files/VZN_o_dani_za_psa_2009.pdf','ine','Čadca'),
('kn-808393','O dani z nehnuteľností 82/2008','https://www.mestocadca.sk/files/VZN_dan_z_nehnutelnosti_2009.pdf','ine','Čadca'),
('kn-808393','O dani za užívanie verejného priestranstva 81/2008','https://www.mestocadca.sk/files/VZN_ver_priestr_schvalene_v_MZ.pdf','ine','Čadca'),
('kn-808393','VZN o mieste a čase zápisu dieťaťa na plnenie povinnej školskej dochádzky do základných škôl 80/2008','https://www.mestocadca.sk/files/vzn-80-2008.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Územného plánu CMZ Čadca - Matičné námestie 79/2008','https://www.mestocadca.sk/files/vzn-79-2008.pdf','text','Čadca'),
('kn-808393','Doplnok k VZN č. 78/2008','https://www.mestocadca.sk/files/doplnok-VZN-c-78-2008.pdf','ine','Čadca'),
('kn-808393','VZN o o výške mesačného príspevku na čiastočnú úhradu nákladov na činnosti školských klubov detí 78/2008','https://www.mestocadca.sk/files/vzn-78-2008.pdf','ine','Čadca'),
('kn-808393','VZN o výške mesačného príspevku na čiastočnú úhradu nákladov spojených so štúdiom v základných umeleckých školách 77/2008','https://www.mestocadca.sk/files/vzn-77-2008.pdf','ine','Čadca'),
('kn-808393','VZN o výške mesačného príspevku na čiastočnú úhradu nákladov na činnosti centra voľného času 76/2008','https://www.mestocadca.sk/files/vzn-76-2008.pdf','ine','Čadca'),
('kn-808393','O výške mesačného príspevku za pobyt dieťaťa v materskej škole na čiastočnú úhradu výdavkov v materských školách na jedno dieťa v zriaďovateľskej pôsobnosti Mesta Čadca 74/2008','https://www.mestocadca.sk/files/VZN_prispevky_skolstvo_pridavky_2008.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Územného plánu mesta Čadca 73/2008','https://www.mestocadca.sk/files/vzn-73-2008.pdf','text','Čadca'),
('kn-808393','O zásadách hospodárenia s bytovým fondom vo vlastníctve mesta Čadca 72/2008','https://www.mestocadca.sk/files/VZN_zasady_bytovy_fond_72-2008.pdf','ine','Čadca'),
('kn-808393','o zásadách hospodárenia s bytovým fondom vo vlastníctve mesta Čadca 72/2008','https://www.mestocadca.sk/files/VZN-72-2008-Zasady-pridelovanie-najomnych-bytov.pdf','ine','Čadca'),
('kn-808393','O prevode vlastníctva bytov a nebytových priestorov 71/2008','https://www.mestocadca.sk/files/VZN-o-prevode-vlastnictva-bytov-a-nb.pdf','ine','Čadca'),
('kn-808393','O podmienkach držania psov na území mesta Čadca 70/2008 - zrušené','https://www.mestocadca.sk/files/VZN-o-podmienkach-dzžania-psov-na-uzemi-mesta-Cadca.pdf','ine','Čadca'),
('kn-808393','O dani za psa 69/2007','https://www.mestocadca.sk/files/VZN-mesta-Cadca-o-dani-za-psa-cislo-69-2007.pdf','ine','Čadca'),
('kn-808393','O dani z nehnuteľnosti 68/2007','https://www.mestocadca.sk/files/VZN-mesta-Cadca-o-dani-z-nehnutelnosti-cislo-68-2007.pdf','ine','Čadca'),
('kn-808393','O dani za nevýherné hracie prístroje 65/2007','https://www.mestocadca.sk/files/VZN-mesta-Cadca-o-dani-za-nevyherne-hracie-pristroje-cislo-65-2007.pdf','ine','Čadca'),
('kn-808393','O dani za predajné automaty 64/2007','https://www.mestocadca.sk/files/VZN-mesta-Cadca-o-dani-za-predajne-automaty-cislo-64-2007.pdf','ine','Čadca'),
('kn-808393','O dani za ubytovanie 63/2007','https://www.mestocadca.sk/files/VZN-mesta-Cadca-o-dani-za-ubytovanie-cislo-63-2007.pdf','ine','Čadca'),
('kn-808393','O školských obvodoch základných škôl v zriaďovateľskej pôsobnosti Mesta Čadca 61/2007','https://www.mestocadca.sk/files/VZN-o-skolskych-obvodoch-zakladnych-skol-v-zriadovatelskej-posobnosti-mesta-Cadca-cislo-61-2007.pdf','ine','Čadca'),
('kn-808393','O tvorbe a ochrane zelene v meste Čadca 58/2007 - zrušené','https://www.mestocadca.sk/files/VZN-mesta-Cadca-o-tvorbe-udrzbe-a-ochrane-zelene-v-meste-Cadca-cislo-58-2007.pdf','ine','Čadca'),
('kn-808393','VZN o záväznej časti Územného plánu mesta Čadca 57/2007','https://www.mestocadca.sk/files/vzn-96-2007.pdf','text','Čadca'),
('kn-808393','O reklamných, informačných a propagačných zariadeniach na území mesta Čadca 49/2006','https://www.mestocadca.sk/files/VZN-c-49-o-reklamnych-informacnych-a-propagacnych-zariadeniach-na-uzemi-mesta-Cadca.pdf','ine','Čadca'),
('kn-808393','O prevádzkovom poriadku pohrebiska','https://www.mestocadca.sk/files/VZN-o-prevadzkovom-poriadku-pohrebiska-Cintorinsky-poriadok.pdf','ine','Čadca'),
('kn-808393','Podmienky poskytovania dotácií z rozpočtu mesta 40/2005','https://www.mestocadca.sk/files/VZN-mesta-Cadca-c-40-zo-dna-28-4-2005-o-poskytovani-dotacii-z-rozpoctu-mesta-z-vlastnych-prijmov.pdf','ine','Čadca'),
('kn-808393','Určunie pravidliel času predaja v obchode a času prevádzky služieb','https://www.mestocadca.sk/files/VZN-mesta-Cadca-ktorym-sa-urcuju-pravidla-casu-predaja-v-obchode-casu-prevadzky-sluzieb..pdf','ine','Čadca'),
('kn-808393','O parkovaní a státí motorových vozidiel na miestnych komunikáciách a verejných priestranstvách v meste Čadca 50/1999','https://www.mestocadca.sk/files/vzn-50-1999.pdf','ine','Čadca'),
('kn-808393','Vymedzenie pojmu služobného tajomstva, upravenie podmienok na jeho ochranu, práva a povinnosti mesta 13/2001','https://www.mestocadca.sk/files/vzn-13-2001.pdf','ine','Čadca'),
('kn-808393','O čistote mesta, ochrane a tvorbe životného prostredia na území mesta Čadca - zrušené','https://www.mestocadca.sk/files/VZN-o-cistote-mesta-ochrane-a-tvorbe-zivotneho-prostredia-na-uzemi-mesta-Cadca.pdf','ine','Čadca'),
('kn-808393','O podmienkach predaja výrobkov a poskytovania služieb na trhových miestach v Meste Čadca /1998','https://www.mestocadca.sk/files/VZN-o-podmienkach-predaja-vyrobkov-a-poskytovania-sluzieb.pdf','ine','Čadca'),
('kn-808393','O podmienkach vylepovania plagátov na verejných priestranstvách a vitrínach /2002','https://www.mestocadca.sk/files/VZN-o-podmienkach-vylepovania-plagatov-na-verejnych-priestranstvach-a-vo-vitrinach.pdf','ine','Čadca'),
('kn-808393','O verejnom poriadku na území mesta Čadca /1997','https://www.mestocadca.sk/files/VZN-o-verejnom-poriadku-na-uzemi-mesta-Cadca.pdf','ine','Čadca');
