/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SystemRouteImport } from './routes/system'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as PrilezitostiRouteImport } from './routes/prilezitosti'
import { Route as VysporiadanieRouteImport } from './routes/vysporiadanie'
import { Route as StavebnePozemkyRouteImport } from './routes/stavebne-pozemky'
import { Route as ZdedeneBytyRouteImport } from './routes/zdedene-byty'
import { Route as PodaNaByvanieRouteImport } from './routes/poda-na-byvanie'
import { Route as PrieskumRouteImport } from './routes/prieskum'
import { Route as DealRadarRouteImport } from './routes/deal-radar'
import { Route as AktivitaRouteImport } from './routes/aktivita'
import { Route as PrehladRouteImport } from './routes/prehlad'
import { Route as KalibraciaRouteImport } from './routes/kalibracia'
import { Route as PoklesyRouteImport } from './routes/poklesy'
import { Route as RanoRouteImport } from './routes/rano'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ZmenyRouteImport } from './routes/zmeny'
import { Route as TrhovaHistoriaRouteImport } from './routes/trhova-historia'
import { Route as ReportyIndexRouteImport } from './routes/reporty.index'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ZoningRouteImport } from './routes/zoning'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportyIdRouteImport } from './routes/reporty.$id'
import { Route as VypisDatasetIdLvNoRouteImport } from './routes/vypis.$datasetId.$lvNo'
import { Route as ReportDatasetIdParcelNoRouteImport } from './routes/report.$datasetId.$parcelNo'
import { Route as KlientReportScenarioKodKuRouteImport } from './routes/klient-report.$scenario.$kodKu'
import { Route as ElDatasetIdCelokRouteImport } from './routes/el.$datasetId.$celok'
import { Route as DatasetyIndexRouteImport } from './routes/datasety.index'
import { Route as DatasetyIdRouteImport } from './routes/datasety.$id'
import { Route as UpInfoIdRouteImport } from './routes/upinfo.$id'
import { Route as OgcRouteImport } from './routes/ogc'
import { Route as MapproxyRouteImport } from './routes/mapproxy'
import { Route as ApiRunAlertsRouteImport } from './routes/api.run-alerts'
import { Route as ApiIngestChangesRouteImport } from './routes/api.ingest-changes'
import { Route as ApiIngestAcquisitionsRouteImport } from './routes/api.ingest-acquisitions'
import { Route as ApiIngestLandsearchRouteImport } from './routes/api.ingest-landsearch'
import { Route as ApiIngestZaRouteImport } from './routes/api.ingest-za'
import { Route as ApiIngestUpRouteImport } from './routes/api.ingest-up'
import { Route as ApiIngestScenarioRunRouteImport } from './routes/api.ingest-scenario-run'
import { Route as ApiIngestSettlementRouteImport } from './routes/api.ingest-settlement'
import { Route as ApiIngestParcelZoningRouteImport } from './routes/api.ingest-parcel-zoning'
import { Route as ApiIngestMarketRouteImport } from './routes/api.ingest-market'
import { Route as ApiIngestDatasetRouteImport } from './routes/api.ingest-dataset'
import { Route as VlastniciRouteImport } from './routes/vlastnici'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as PravnyReferentRouteImport } from './routes/pravny-referent'
import { Route as CenyRouteImport } from './routes/ceny'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrilezitostiRoute = PrilezitostiRouteImport.update({
  id: '/prilezitosti',
  path: '/prilezitosti',
  getParentRoute: () => rootRouteImport,
} as any)
const VysporiadanieRoute = VysporiadanieRouteImport.update({
  id: '/vysporiadanie',
  path: '/vysporiadanie',
  getParentRoute: () => rootRouteImport,
} as any)
const StavebnePozemkyRoute = StavebnePozemkyRouteImport.update({
  id: '/stavebne-pozemky',
  path: '/stavebne-pozemky',
  getParentRoute: () => rootRouteImport,
} as any)
const ZdedeneBytyRoute = ZdedeneBytyRouteImport.update({
  id: '/zdedene-byty',
  path: '/zdedene-byty',
  getParentRoute: () => rootRouteImport,
} as any)
const PodaNaByvanieRoute = PodaNaByvanieRouteImport.update({
  id: '/poda-na-byvanie',
  path: '/poda-na-byvanie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrieskumRoute = PrieskumRouteImport.update({
  id: '/prieskum',
  path: '/prieskum',
  getParentRoute: () => rootRouteImport,
} as any)
const DealRadarRoute = DealRadarRouteImport.update({
  id: '/deal-radar',
  path: '/deal-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivitaRoute = AktivitaRouteImport.update({
  id: '/aktivita',
  path: '/aktivita',
  getParentRoute: () => rootRouteImport,
} as any)
const KalibraciaRoute = KalibraciaRouteImport.update({
  id: '/kalibracia',
  path: '/kalibracia',
  getParentRoute: () => rootRouteImport,
} as any)
const PrehladRoute = PrehladRouteImport.update({
  id: '/prehlad',
  path: '/prehlad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoklesyRoute = PoklesyRouteImport.update({
  id: '/poklesy',
  path: '/poklesy',
  getParentRoute: () => rootRouteImport,
} as any)
const RanoRoute = RanoRouteImport.update({
  id: '/rano',
  path: '/rano',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ZmenyRoute = ZmenyRouteImport.update({
  id: '/zmeny',
  path: '/zmeny',
  getParentRoute: () => rootRouteImport,
} as any)
const TrhovaHistoriaRoute = TrhovaHistoriaRouteImport.update({
  id: '/trhova-historia',
  path: '/trhova-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportyIndexRoute = ReportyIndexRouteImport.update({
  id: '/reporty/',
  path: '/reporty/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoningRoute = ZoningRouteImport.update({
  id: '/zoning',
  path: '/zoning',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportyIdRoute = ReportyIdRouteImport.update({
  id: '/reporty/$id',
  path: '/reporty/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VypisDatasetIdLvNoRoute = VypisDatasetIdLvNoRouteImport.update({
  id: '/vypis/$datasetId/$lvNo',
  path: '/vypis/$datasetId/$lvNo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDatasetIdParcelNoRoute = ReportDatasetIdParcelNoRouteImport.update({
  id: '/report/$datasetId/$parcelNo',
  path: '/report/$datasetId/$parcelNo',
  getParentRoute: () => rootRouteImport,
} as any)
const KlientReportScenarioKodKuRoute = KlientReportScenarioKodKuRouteImport.update({
  id: '/klient-report/$scenario/$kodKu',
  path: '/klient-report/$scenario/$kodKu',
  getParentRoute: () => rootRouteImport,
} as any)
const ElDatasetIdCelokRoute = ElDatasetIdCelokRouteImport.update({
  id: '/el/$datasetId/$celok',
  path: '/el/$datasetId/$celok',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetyIndexRoute = DatasetyIndexRouteImport.update({
  id: '/datasety/',
  path: '/datasety/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetyIdRoute = DatasetyIdRouteImport.update({
  id: '/datasety/$id',
  path: '/datasety/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UpInfoIdRoute = UpInfoIdRouteImport.update({
  id: '/upinfo/$id',
  path: '/upinfo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgcRoute = OgcRouteImport.update({
  id: '/ogc',
  path: '/ogc',
  getParentRoute: () => rootRouteImport,
} as any)
const MapproxyRoute = MapproxyRouteImport.update({
  id: '/mapproxy',
  path: '/mapproxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunAlertsRoute = ApiRunAlertsRouteImport.update({
  id: '/api/run-alerts',
  path: '/api/run-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestChangesRoute = ApiIngestChangesRouteImport.update({
  id: '/api/ingest-changes',
  path: '/api/ingest-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestAcquisitionsRoute = ApiIngestAcquisitionsRouteImport.update({
  id: '/api/ingest-acquisitions',
  path: '/api/ingest-acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestLandsearchRoute = ApiIngestLandsearchRouteImport.update({
  id: '/api/ingest-landsearch',
  path: '/api/ingest-landsearch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestZaRoute = ApiIngestZaRouteImport.update({
  id: '/api/ingest-za',
  path: '/api/ingest-za',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestUpRoute = ApiIngestUpRouteImport.update({
  id: '/api/ingest-up',
  path: '/api/ingest-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestScenarioRunRoute = ApiIngestScenarioRunRouteImport.update({
  id: '/api/ingest-scenario-run',
  path: '/api/ingest-scenario-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSettlementRoute = ApiIngestSettlementRouteImport.update({
  id: '/api/ingest-settlement',
  path: '/api/ingest-settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestParcelZoningRoute = ApiIngestParcelZoningRouteImport.update({
  id: '/api/ingest-parcel-zoning',
  path: '/api/ingest-parcel-zoning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestMarketRoute = ApiIngestMarketRouteImport.update({
  id: '/api/ingest-market',
  path: '/api/ingest-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestDatasetRoute = ApiIngestDatasetRouteImport.update({
  id: '/api/ingest-dataset',
  path: '/api/ingest-dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const VlastniciRoute = VlastniciRouteImport.update({
  id: '/vlastnici',
  path: '/vlastnici',
  getParentRoute: () => rootRouteImport,
} as any)
const PravnyReferentRoute = PravnyReferentRouteImport.update({
  id: '/pravny-referent',
  path: '/pravny-referent',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/vysporiadanie': typeof VysporiadanieRoute
  '/stavebne-pozemky': typeof StavebnePozemkyRoute
  '/zdedene-byty': typeof ZdedeneBytyRoute
  '/poda-na-byvanie': typeof PodaNaByvanieRoute
  '/api/ingest-za': typeof ApiIngestZaRoute
  '/api/ingest-up': typeof ApiIngestUpRoute
  '/api/ingest-scenario-run': typeof ApiIngestScenarioRunRoute
  '/api/ingest-settlement': typeof ApiIngestSettlementRoute
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/browser': typeof BrowserRoute
  '/vlastnici': typeof VlastniciRoute
  '/zoning': typeof ZoningRoute
  '/cases': typeof CasesRoute
  '/deals': typeof DealsRoute
  '/import': typeof ImportRoute
  '/reporty': typeof ReportyIndexRoute
  '/prilezitosti': typeof PrilezitostiRoute
  '/prieskum': typeof PrieskumRoute
  '/deal-radar': typeof DealRadarRoute
  '/aktivita': typeof AktivitaRoute
  '/prehlad': typeof PrehladRoute
  '/kalibracia': typeof KalibraciaRoute
  '/poklesy': typeof PoklesyRoute
  '/rano': typeof RanoRoute
  '/watchlist': typeof WatchlistRoute
  '/zmeny': typeof ZmenyRoute
  '/trhova-historia': typeof TrhovaHistoriaRoute
  '/pravny-referent': typeof PravnyReferentRoute
  '/ceny': typeof CenyRoute
  '/system': typeof SystemRoute
  '/gdpr': typeof GdprRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ogc': typeof OgcRoute
  '/mapproxy': typeof MapproxyRoute
  '/api/run-alerts': typeof ApiRunAlertsRoute
  '/api/ingest-changes': typeof ApiIngestChangesRoute
  '/api/ingest-acquisitions': typeof ApiIngestAcquisitionsRoute
  '/api/ingest-landsearch': typeof ApiIngestLandsearchRoute
  '/api/ingest-parcel-zoning': typeof ApiIngestParcelZoningRoute
  '/api/ingest-market': typeof ApiIngestMarketRoute
  '/api/ingest-dataset': typeof ApiIngestDatasetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reporty/$id': typeof ReportyIdRoute
  '/vypis/$datasetId/$lvNo': typeof VypisDatasetIdLvNoRoute
  '/report/$datasetId/$parcelNo': typeof ReportDatasetIdParcelNoRoute
  '/klient-report/$scenario/$kodKu': typeof KlientReportScenarioKodKuRoute
  '/el/$datasetId/$celok': typeof ElDatasetIdCelokRoute
  '/upinfo/$id': typeof UpInfoIdRoute
  '/datasety/$id': typeof DatasetyIdRoute
  '/datasety': typeof DatasetyIndexRoute
}
export interface FileRoutesByTo {
  '/vysporiadanie': typeof VysporiadanieRoute
  '/stavebne-pozemky': typeof StavebnePozemkyRoute
  '/zdedene-byty': typeof ZdedeneBytyRoute
  '/poda-na-byvanie': typeof PodaNaByvanieRoute
  '/api/ingest-za': typeof ApiIngestZaRoute
  '/api/ingest-up': typeof ApiIngestUpRoute
  '/api/ingest-scenario-run': typeof ApiIngestScenarioRunRoute
  '/api/ingest-settlement': typeof ApiIngestSettlementRoute
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/browser': typeof BrowserRoute
  '/vlastnici': typeof VlastniciRoute
  '/zoning': typeof ZoningRoute
  '/cases': typeof CasesRoute
  '/deals': typeof DealsRoute
  '/import': typeof ImportRoute
  '/reporty': typeof ReportyIndexRoute
  '/prilezitosti': typeof PrilezitostiRoute
  '/prieskum': typeof PrieskumRoute
  '/deal-radar': typeof DealRadarRoute
  '/aktivita': typeof AktivitaRoute
  '/prehlad': typeof PrehladRoute
  '/kalibracia': typeof KalibraciaRoute
  '/poklesy': typeof PoklesyRoute
  '/rano': typeof RanoRoute
  '/watchlist': typeof WatchlistRoute
  '/zmeny': typeof ZmenyRoute
  '/trhova-historia': typeof TrhovaHistoriaRoute
  '/pravny-referent': typeof PravnyReferentRoute
  '/ceny': typeof CenyRoute
  '/system': typeof SystemRoute
  '/gdpr': typeof GdprRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ogc': typeof OgcRoute
  '/mapproxy': typeof MapproxyRoute
  '/api/run-alerts': typeof ApiRunAlertsRoute
  '/api/ingest-changes': typeof ApiIngestChangesRoute
  '/api/ingest-acquisitions': typeof ApiIngestAcquisitionsRoute
  '/api/ingest-landsearch': typeof ApiIngestLandsearchRoute
  '/api/ingest-parcel-zoning': typeof ApiIngestParcelZoningRoute
  '/api/ingest-market': typeof ApiIngestMarketRoute
  '/api/ingest-dataset': typeof ApiIngestDatasetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reporty/$id': typeof ReportyIdRoute
  '/vypis/$datasetId/$lvNo': typeof VypisDatasetIdLvNoRoute
  '/report/$datasetId/$parcelNo': typeof ReportDatasetIdParcelNoRoute
  '/klient-report/$scenario/$kodKu': typeof KlientReportScenarioKodKuRoute
  '/el/$datasetId/$celok': typeof ElDatasetIdCelokRoute
  '/upinfo/$id': typeof UpInfoIdRoute
  '/datasety/$id': typeof DatasetyIdRoute
  '/datasety': typeof DatasetyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/vysporiadanie': typeof VysporiadanieRoute
  '/stavebne-pozemky': typeof StavebnePozemkyRoute
  '/zdedene-byty': typeof ZdedeneBytyRoute
  '/poda-na-byvanie': typeof PodaNaByvanieRoute
  '/api/ingest-za': typeof ApiIngestZaRoute
  '/api/ingest-up': typeof ApiIngestUpRoute
  '/api/ingest-scenario-run': typeof ApiIngestScenarioRunRoute
  '/api/ingest-settlement': typeof ApiIngestSettlementRoute
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/browser': typeof BrowserRoute
  '/vlastnici': typeof VlastniciRoute
  '/zoning': typeof ZoningRoute
  '/cases': typeof CasesRoute
  '/deals': typeof DealsRoute
  '/import': typeof ImportRoute
  '/reporty/': typeof ReportyIndexRoute
  '/prilezitosti': typeof PrilezitostiRoute
  '/prieskum': typeof PrieskumRoute
  '/deal-radar': typeof DealRadarRoute
  '/aktivita': typeof AktivitaRoute
  '/prehlad': typeof PrehladRoute
  '/kalibracia': typeof KalibraciaRoute
  '/poklesy': typeof PoklesyRoute
  '/rano': typeof RanoRoute
  '/watchlist': typeof WatchlistRoute
  '/zmeny': typeof ZmenyRoute
  '/trhova-historia': typeof TrhovaHistoriaRoute
  '/pravny-referent': typeof PravnyReferentRoute
  '/ceny': typeof CenyRoute
  '/system': typeof SystemRoute
  '/gdpr': typeof GdprRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ogc': typeof OgcRoute
  '/mapproxy': typeof MapproxyRoute
  '/api/run-alerts': typeof ApiRunAlertsRoute
  '/api/ingest-changes': typeof ApiIngestChangesRoute
  '/api/ingest-acquisitions': typeof ApiIngestAcquisitionsRoute
  '/api/ingest-landsearch': typeof ApiIngestLandsearchRoute
  '/api/ingest-parcel-zoning': typeof ApiIngestParcelZoningRoute
  '/api/ingest-market': typeof ApiIngestMarketRoute
  '/api/ingest-dataset': typeof ApiIngestDatasetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reporty/$id': typeof ReportyIdRoute
  '/vypis/$datasetId/$lvNo': typeof VypisDatasetIdLvNoRoute
  '/report/$datasetId/$parcelNo': typeof ReportDatasetIdParcelNoRoute
  '/klient-report/$scenario/$kodKu': typeof KlientReportScenarioKodKuRoute
  '/el/$datasetId/$celok': typeof ElDatasetIdCelokRoute
  '/upinfo/$id': typeof UpInfoIdRoute
  '/datasety/$id': typeof DatasetyIdRoute
  '/datasety/': typeof DatasetyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/vysporiadanie'
    | '/stavebne-pozemky'
    | '/zdedene-byty'
    | '/poda-na-byvanie'
    | '/api/ingest-za'
    | '/api/ingest-up'
    | '/api/ingest-scenario-run'
    | '/api/ingest-settlement'
    | '/'
    | '/mapa'
    | '/browser'
    | '/vlastnici'
    | '/zoning'
    | '/cases'
    | '/deals'
    | '/import'
    | '/reporty'
    | '/prilezitosti'
    | '/prieskum'
    | '/deal-radar'
    | '/aktivita'
    | '/prehlad'
    | '/kalibracia'
    | '/poklesy'
    | '/rano'
    | '/watchlist'
    | '/zmeny'
    | '/trhova-historia'
    | '/pravny-referent'
    | '/ceny'
    | '/system'
    | '/gdpr'
    | '/robots.txt'
    | '/ogc'
    | '/mapproxy'
    | '/api/run-alerts'
    | '/api/ingest-changes'
    | '/api/ingest-acquisitions'
    | '/api/ingest-landsearch'
    | '/api/ingest-parcel-zoning'
    | '/api/ingest-market'
    | '/api/ingest-dataset'
    | '/sitemap.xml'
    | '/reporty/$id'
    | '/vypis/$datasetId/$lvNo'
    | '/report/$datasetId/$parcelNo'
    | '/klient-report/$scenario/$kodKu'
    | '/el/$datasetId/$celok'
    | '/upinfo/$id'
    | '/datasety/$id'
    | '/datasety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/vysporiadanie'
    | '/stavebne-pozemky'
    | '/zdedene-byty'
    | '/poda-na-byvanie'
    | '/api/ingest-za'
    | '/api/ingest-up'
    | '/api/ingest-scenario-run'
    | '/api/ingest-settlement'
    | '/'
    | '/mapa'
    | '/browser'
    | '/vlastnici'
    | '/zoning'
    | '/cases'
    | '/deals'
    | '/import'
    | '/reporty'
    | '/prilezitosti'
    | '/prieskum'
    | '/deal-radar'
    | '/aktivita'
    | '/prehlad'
    | '/kalibracia'
    | '/poklesy'
    | '/rano'
    | '/watchlist'
    | '/zmeny'
    | '/trhova-historia'
    | '/pravny-referent'
    | '/ceny'
    | '/system'
    | '/gdpr'
    | '/robots.txt'
    | '/ogc'
    | '/mapproxy'
    | '/api/run-alerts'
    | '/api/ingest-changes'
    | '/api/ingest-acquisitions'
    | '/api/ingest-landsearch'
    | '/api/ingest-parcel-zoning'
    | '/api/ingest-market'
    | '/api/ingest-dataset'
    | '/sitemap.xml'
    | '/reporty/$id'
    | '/vypis/$datasetId/$lvNo'
    | '/report/$datasetId/$parcelNo'
    | '/klient-report/$scenario/$kodKu'
    | '/el/$datasetId/$celok'
    | '/upinfo/$id'
    | '/datasety/$id'
    | '/datasety'
  id:
    | '__root__'
    | '/vysporiadanie'
    | '/stavebne-pozemky'
    | '/zdedene-byty'
    | '/poda-na-byvanie'
    | '/api/ingest-za'
    | '/api/ingest-up'
    | '/api/ingest-scenario-run'
    | '/api/ingest-settlement'
    | '/'
    | '/mapa'
    | '/browser'
    | '/vlastnici'
    | '/zoning'
    | '/cases'
    | '/deals'
    | '/import'
    | '/reporty/'
    | '/prilezitosti'
    | '/prieskum'
    | '/deal-radar'
    | '/aktivita'
    | '/prehlad'
    | '/kalibracia'
    | '/poklesy'
    | '/rano'
    | '/watchlist'
    | '/zmeny'
    | '/trhova-historia'
    | '/pravny-referent'
    | '/ceny'
    | '/system'
    | '/gdpr'
    | '/robots.txt'
    | '/ogc'
    | '/mapproxy'
    | '/api/run-alerts'
    | '/api/ingest-changes'
    | '/api/ingest-acquisitions'
    | '/api/ingest-landsearch'
    | '/api/ingest-parcel-zoning'
    | '/api/ingest-market'
    | '/api/ingest-dataset'
    | '/sitemap.xml'
    | '/reporty/$id'
    | '/upinfo/$id'
    | '/datasety/$id'
    | '/datasety/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VysporiadanieRoute: typeof VysporiadanieRoute
  StavebnePozemkyRoute: typeof StavebnePozemkyRoute
  ZdedeneBytyRoute: typeof ZdedeneBytyRoute
  PodaNaByvanieRoute: typeof PodaNaByvanieRoute
  ApiIngestZaRoute: typeof ApiIngestZaRoute
  ApiIngestUpRoute: typeof ApiIngestUpRoute
  ApiIngestScenarioRunRoute: typeof ApiIngestScenarioRunRoute
  ApiIngestSettlementRoute: typeof ApiIngestSettlementRoute
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  BrowserRoute: typeof BrowserRoute
  VlastniciRoute: typeof VlastniciRoute
  ZoningRoute: typeof ZoningRoute
  CasesRoute: typeof CasesRoute
  DealsRoute: typeof DealsRoute
  ImportRoute: typeof ImportRoute
  ReportyIndexRoute: typeof ReportyIndexRoute
  PrilezitostiRoute: typeof PrilezitostiRoute
  PrieskumRoute: typeof PrieskumRoute
  DealRadarRoute: typeof DealRadarRoute
  AktivitaRoute: typeof AktivitaRoute
  PrehladRoute: typeof PrehladRoute
  KalibraciaRoute: typeof KalibraciaRoute
  PoklesyRoute: typeof PoklesyRoute
  RanoRoute: typeof RanoRoute
  WatchlistRoute: typeof WatchlistRoute
  ZmenyRoute: typeof ZmenyRoute
  TrhovaHistoriaRoute: typeof TrhovaHistoriaRoute
  PravnyReferentRoute: typeof PravnyReferentRoute
  CenyRoute: typeof CenyRoute
  SystemRoute: typeof SystemRoute
  GdprRoute: typeof GdprRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OgcRoute: typeof OgcRoute
  MapproxyRoute: typeof MapproxyRoute
  ApiRunAlertsRoute: typeof ApiRunAlertsRoute
  ApiIngestChangesRoute: typeof ApiIngestChangesRoute
  ApiIngestAcquisitionsRoute: typeof ApiIngestAcquisitionsRoute
  ApiIngestLandsearchRoute: typeof ApiIngestLandsearchRoute
  ApiIngestParcelZoningRoute: typeof ApiIngestParcelZoningRoute
  ApiIngestMarketRoute: typeof ApiIngestMarketRoute
  ApiIngestDatasetRoute: typeof ApiIngestDatasetRoute
  ReportyIdRoute: typeof ReportyIdRoute
  VypisDatasetIdLvNoRoute: typeof VypisDatasetIdLvNoRoute
  ReportDatasetIdParcelNoRoute: typeof ReportDatasetIdParcelNoRoute
  KlientReportScenarioKodKuRoute: typeof KlientReportScenarioKodKuRoute
  ElDatasetIdCelokRoute: typeof ElDatasetIdCelokRoute
  UpInfoIdRoute: typeof UpInfoIdRoute
  DatasetyIdRoute: typeof DatasetyIdRoute
  DatasetyIndexRoute: typeof DatasetyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogc': {
      id: '/ogc'
      path: '/ogc'
      fullPath: '/ogc'
      preLoaderRoute: typeof OgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapproxy': {
      id: '/mapproxy'
      path: '/mapproxy'
      fullPath: '/mapproxy'
      preLoaderRoute: typeof MapproxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-changes': {
      id: '/api/ingest-changes'
      path: '/api/ingest-changes'
      fullPath: '/api/ingest-changes'
      preLoaderRoute: typeof ApiIngestChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-acquisitions': {
      id: '/api/ingest-acquisitions'
      path: '/api/ingest-acquisitions'
      fullPath: '/api/ingest-acquisitions'
      preLoaderRoute: typeof ApiIngestAcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-landsearch': {
      id: '/api/ingest-landsearch'
      path: '/api/ingest-landsearch'
      fullPath: '/api/ingest-landsearch'
      preLoaderRoute: typeof ApiIngestLandsearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-parcel-zoning': {
      id: '/api/ingest-parcel-zoning'
      path: '/api/ingest-parcel-zoning'
      fullPath: '/api/ingest-parcel-zoning'
      preLoaderRoute: typeof ApiIngestParcelZoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-market': {
      id: '/api/ingest-market'
      path: '/api/ingest-market'
      fullPath: '/api/ingest-market'
      preLoaderRoute: typeof ApiIngestMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-dataset': {
      id: '/api/ingest-dataset'
      path: '/api/ingest-dataset'
      fullPath: '/api/ingest-dataset'
      preLoaderRoute: typeof ApiIngestDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-alerts': {
      id: '/api/run-alerts'
      path: '/api/run-alerts'
      fullPath: '/api/run-alerts'
      preLoaderRoute: typeof ApiRunAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prilezitosti': {
      id: '/prilezitosti'
      path: '/prilezitosti'
      fullPath: '/prilezitosti'
      preLoaderRoute: typeof PrilezitostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vysporiadanie': {
      id: '/vysporiadanie'
      path: '/vysporiadanie'
      fullPath: '/vysporiadanie'
      preLoaderRoute: typeof VysporiadanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stavebne-pozemky': {
      id: '/stavebne-pozemky'
      path: '/stavebne-pozemky'
      fullPath: '/stavebne-pozemky'
      preLoaderRoute: typeof StavebnePozemkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zdedene-byty': {
      id: '/zdedene-byty'
      path: '/zdedene-byty'
      fullPath: '/zdedene-byty'
      preLoaderRoute: typeof ZdedeneBytyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poda-na-byvanie': {
      id: '/poda-na-byvanie'
      path: '/poda-na-byvanie'
      fullPath: '/poda-na-byvanie'
      preLoaderRoute: typeof PodaNaByvanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-za': {
      id: '/api/ingest-za'
      path: '/api/ingest-za'
      fullPath: '/api/ingest-za'
      preLoaderRoute: typeof ApiIngestZaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-up': {
      id: '/api/ingest-up'
      path: '/api/ingest-up'
      fullPath: '/api/ingest-up'
      preLoaderRoute: typeof ApiIngestUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-scenario-run': {
      id: '/api/ingest-scenario-run'
      path: '/api/ingest-scenario-run'
      fullPath: '/api/ingest-scenario-run'
      preLoaderRoute: typeof ApiIngestScenarioRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-settlement': {
      id: '/api/ingest-settlement'
      path: '/api/ingest-settlement'
      fullPath: '/api/ingest-settlement'
      preLoaderRoute: typeof ApiIngestSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prieskum': {
      id: '/prieskum'
      path: '/prieskum'
      fullPath: '/prieskum'
      preLoaderRoute: typeof PrieskumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-radar': {
      id: '/deal-radar'
      path: '/deal-radar'
      fullPath: '/deal-radar'
      preLoaderRoute: typeof DealRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivita': {
      id: '/aktivita'
      path: '/aktivita'
      fullPath: '/aktivita'
      preLoaderRoute: typeof AktivitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalibracia': {
      id: '/kalibracia'
      path: '/kalibracia'
      fullPath: '/kalibracia'
      preLoaderRoute: typeof KalibraciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prehlad': {
      id: '/prehlad'
      path: '/prehlad'
      fullPath: '/prehlad'
      preLoaderRoute: typeof PrehladRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poklesy': {
      id: '/poklesy'
      path: '/poklesy'
      fullPath: '/poklesy'
      preLoaderRoute: typeof PoklesyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rano': {
      id: '/rano'
      path: '/rano'
      fullPath: '/rano'
      preLoaderRoute: typeof RanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/zmeny': {
      id: '/zmeny'
      path: '/zmeny'
      fullPath: '/zmeny'
      preLoaderRoute: typeof ZmenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trhova-historia': {
      id: '/trhova-historia'
      path: '/trhova-historia'
      fullPath: '/trhova-historia'
      preLoaderRoute: typeof TrhovaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporty/': {
      id: '/reporty/'
      path: '/reporty'
      fullPath: '/reporty'
      preLoaderRoute: typeof ReportyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoning': {
      id: '/zoning'
      path: '/zoning'
      fullPath: '/zoning'
      preLoaderRoute: typeof ZoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vlastnici': {
      id: '/vlastnici'
      path: '/vlastnici'
      fullPath: '/vlastnici'
      preLoaderRoute: typeof VlastniciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravny-referent': {
      id: '/pravny-referent'
      path: '/pravny-referent'
      fullPath: '/pravny-referent'
      preLoaderRoute: typeof PravnyReferentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporty/$id': {
      id: '/reporty/$id'
      path: '/reporty/$id'
      fullPath: '/reporty/$id'
      preLoaderRoute: typeof ReportyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$datasetId/$parcelNo': {
      id: '/report/$datasetId/$parcelNo'
      path: '/report/$datasetId/$parcelNo'
      fullPath: '/report/$datasetId/$parcelNo'
      preLoaderRoute: typeof ReportDatasetIdParcelNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klient-report/$scenario/$kodKu': {
      id: '/klient-report/$scenario/$kodKu'
      path: '/klient-report/$scenario/$kodKu'
      fullPath: '/klient-report/$scenario/$kodKu'
      preLoaderRoute: typeof KlientReportScenarioKodKuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vypis/$datasetId/$lvNo': {
      id: '/vypis/$datasetId/$lvNo'
      path: '/vypis/$datasetId/$lvNo'
      fullPath: '/vypis/$datasetId/$lvNo'
      preLoaderRoute: typeof VypisDatasetIdLvNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/$datasetId/$celok': {
      id: '/el/$datasetId/$celok'
      path: '/el/$datasetId/$celok'
      fullPath: '/el/$datasetId/$celok'
      preLoaderRoute: typeof ElDatasetIdCelokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upinfo/$id': {
      id: '/upinfo/$id'
      path: '/upinfo/$id'
      fullPath: '/upinfo/$id'
      preLoaderRoute: typeof UpInfoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasety/$id': {
      id: '/datasety/$id'
      path: '/datasety/$id'
      fullPath: '/datasety/$id'
      preLoaderRoute: typeof DatasetyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasety/': {
      id: '/datasety/'
      path: '/datasety'
      fullPath: '/datasety'
      preLoaderRoute: typeof DatasetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  VysporiadanieRoute: VysporiadanieRoute,
  StavebnePozemkyRoute: StavebnePozemkyRoute,
  ZdedeneBytyRoute: ZdedeneBytyRoute,
  PodaNaByvanieRoute: PodaNaByvanieRoute,
  ApiIngestZaRoute: ApiIngestZaRoute,
  ApiIngestUpRoute: ApiIngestUpRoute,
  ApiIngestScenarioRunRoute: ApiIngestScenarioRunRoute,
  ApiIngestSettlementRoute: ApiIngestSettlementRoute,
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  BrowserRoute: BrowserRoute,
  VlastniciRoute: VlastniciRoute,
  ZoningRoute: ZoningRoute,
  CasesRoute: CasesRoute,
  DealsRoute: DealsRoute,
  ImportRoute: ImportRoute,
  ReportyIndexRoute: ReportyIndexRoute,
  PrilezitostiRoute: PrilezitostiRoute,
  PrieskumRoute: PrieskumRoute,
  DealRadarRoute: DealRadarRoute,
  AktivitaRoute: AktivitaRoute,
  PrehladRoute: PrehladRoute,
  KalibraciaRoute: KalibraciaRoute,
  PoklesyRoute: PoklesyRoute,
  RanoRoute: RanoRoute,
  WatchlistRoute: WatchlistRoute,
  ZmenyRoute: ZmenyRoute,
  TrhovaHistoriaRoute: TrhovaHistoriaRoute,
  PravnyReferentRoute: PravnyReferentRoute,
  CenyRoute: CenyRoute,
  SystemRoute: SystemRoute,
  GdprRoute: GdprRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OgcRoute: OgcRoute,
  MapproxyRoute: MapproxyRoute,
  ApiRunAlertsRoute: ApiRunAlertsRoute,
  ApiIngestChangesRoute: ApiIngestChangesRoute,
  ApiIngestAcquisitionsRoute: ApiIngestAcquisitionsRoute,
  ApiIngestLandsearchRoute: ApiIngestLandsearchRoute,
  ApiIngestParcelZoningRoute: ApiIngestParcelZoningRoute,
  ApiIngestMarketRoute: ApiIngestMarketRoute,
  ApiIngestDatasetRoute: ApiIngestDatasetRoute,
  ReportyIdRoute: ReportyIdRoute,
  VypisDatasetIdLvNoRoute: VypisDatasetIdLvNoRoute,
  ReportDatasetIdParcelNoRoute: ReportDatasetIdParcelNoRoute,
  KlientReportScenarioKodKuRoute: KlientReportScenarioKodKuRoute,
  ElDatasetIdCelokRoute: ElDatasetIdCelokRoute,
  UpInfoIdRoute: UpInfoIdRoute,
  DatasetyIdRoute: DatasetyIdRoute,
  DatasetyIndexRoute: DatasetyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
