/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SystemRouteImport } from './routes/system'
import { Route as PrilezitostiRouteImport } from './routes/prilezitosti'
import { Route as PrieskumRouteImport } from './routes/prieskum'
import { Route as DealRadarRouteImport } from './routes/deal-radar'
import { Route as TrhovaHistoriaRouteImport } from './routes/trhova-historia'
import { Route as ReportyRouteImport } from './routes/reporty'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ZoningRouteImport } from './routes/zoning'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportyIdRouteImport } from './routes/reporty.$id'
import { Route as VypisDatasetIdLvNoRouteImport } from './routes/vypis.$datasetId.$lvNo'
import { Route as ElDatasetIdCelokRouteImport } from './routes/el.$datasetId.$celok'
import { Route as DatasetyIndexRouteImport } from './routes/datasety.index'
import { Route as DatasetyIdRouteImport } from './routes/datasety.$id'
import { Route as UpInfoIdRouteImport } from './routes/upinfo.$id'
import { Route as OgcRouteImport } from './routes/ogc'
import { Route as VlastniciRouteImport } from './routes/vlastnici'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as PravnyReferentRouteImport } from './routes/pravny-referent'
import { Route as CenyRouteImport } from './routes/ceny'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const PrilezitostiRoute = PrilezitostiRouteImport.update({
  id: '/prilezitosti',
  path: '/prilezitosti',
  getParentRoute: () => rootRouteImport,
} as any)
const PrieskumRoute = PrieskumRouteImport.update({
  id: '/prieskum',
  path: '/prieskum',
  getParentRoute: () => rootRouteImport,
} as any)
const DealRadarRoute = DealRadarRouteImport.update({
  id: '/deal-radar',
  path: '/deal-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TrhovaHistoriaRoute = TrhovaHistoriaRouteImport.update({
  id: '/trhova-historia',
  path: '/trhova-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportyRoute = ReportyRouteImport.update({
  id: '/reporty',
  path: '/reporty',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoningRoute = ZoningRouteImport.update({
  id: '/zoning',
  path: '/zoning',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportyIdRoute = ReportyIdRouteImport.update({
  id: '/reporty/$id',
  path: '/reporty/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VypisDatasetIdLvNoRoute = VypisDatasetIdLvNoRouteImport.update({
  id: '/vypis/$datasetId/$lvNo',
  path: '/vypis/$datasetId/$lvNo',
  getParentRoute: () => rootRouteImport,
} as any)
const ElDatasetIdCelokRoute = ElDatasetIdCelokRouteImport.update({
  id: '/el/$datasetId/$celok',
  path: '/el/$datasetId/$celok',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetyIndexRoute = DatasetyIndexRouteImport.update({
  id: '/datasety/',
  path: '/datasety/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetyIdRoute = DatasetyIdRouteImport.update({
  id: '/datasety/$id',
  path: '/datasety/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UpInfoIdRoute = UpInfoIdRouteImport.update({
  id: '/upinfo/$id',
  path: '/upinfo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgcRoute = OgcRouteImport.update({
  id: '/ogc',
  path: '/ogc',
  getParentRoute: () => rootRouteImport,
} as any)
const VlastniciRoute = VlastniciRouteImport.update({
  id: '/vlastnici',
  path: '/vlastnici',
  getParentRoute: () => rootRouteImport,
} as any)
const PravnyReferentRoute = PravnyReferentRouteImport.update({
  id: '/pravny-referent',
  path: '/pravny-referent',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/browser': typeof BrowserRoute
  '/vlastnici': typeof VlastniciRoute
  '/zoning': typeof ZoningRoute
  '/cases': typeof CasesRoute
  '/deals': typeof DealsRoute
  '/import': typeof ImportRoute
  '/reporty': typeof ReportyRoute
  '/prilezitosti': typeof PrilezitostiRoute
  '/prieskum': typeof PrieskumRoute
  '/deal-radar': typeof DealRadarRoute
  '/trhova-historia': typeof TrhovaHistoriaRoute
  '/pravny-referent': typeof PravnyReferentRoute
  '/ceny': typeof CenyRoute
  '/system': typeof SystemRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ogc': typeof OgcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reporty/$id': typeof ReportyIdRoute
  '/vypis/$datasetId/$lvNo': typeof VypisDatasetIdLvNoRoute
  '/el/$datasetId/$celok': typeof ElDatasetIdCelokRoute
  '/upinfo/$id': typeof UpInfoIdRoute
  '/datasety/$id': typeof DatasetyIdRoute
  '/datasety': typeof DatasetyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/browser': typeof BrowserRoute
  '/vlastnici': typeof VlastniciRoute
  '/zoning': typeof ZoningRoute
  '/cases': typeof CasesRoute
  '/deals': typeof DealsRoute
  '/import': typeof ImportRoute
  '/reporty': typeof ReportyRoute
  '/prilezitosti': typeof PrilezitostiRoute
  '/prieskum': typeof PrieskumRoute
  '/deal-radar': typeof DealRadarRoute
  '/trhova-historia': typeof TrhovaHistoriaRoute
  '/pravny-referent': typeof PravnyReferentRoute
  '/ceny': typeof CenyRoute
  '/system': typeof SystemRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ogc': typeof OgcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reporty/$id': typeof ReportyIdRoute
  '/vypis/$datasetId/$lvNo': typeof VypisDatasetIdLvNoRoute
  '/el/$datasetId/$celok': typeof ElDatasetIdCelokRoute
  '/upinfo/$id': typeof UpInfoIdRoute
  '/datasety/$id': typeof DatasetyIdRoute
  '/datasety': typeof DatasetyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/browser': typeof BrowserRoute
  '/vlastnici': typeof VlastniciRoute
  '/zoning': typeof ZoningRoute
  '/cases': typeof CasesRoute
  '/deals': typeof DealsRoute
  '/import': typeof ImportRoute
  '/reporty': typeof ReportyRoute
  '/prilezitosti': typeof PrilezitostiRoute
  '/prieskum': typeof PrieskumRoute
  '/deal-radar': typeof DealRadarRoute
  '/trhova-historia': typeof TrhovaHistoriaRoute
  '/pravny-referent': typeof PravnyReferentRoute
  '/ceny': typeof CenyRoute
  '/system': typeof SystemRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ogc': typeof OgcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reporty/$id': typeof ReportyIdRoute
  '/vypis/$datasetId/$lvNo': typeof VypisDatasetIdLvNoRoute
  '/el/$datasetId/$celok': typeof ElDatasetIdCelokRoute
  '/upinfo/$id': typeof UpInfoIdRoute
  '/datasety/$id': typeof DatasetyIdRoute
  '/datasety/': typeof DatasetyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapa'
    | '/browser'
    | '/vlastnici'
    | '/zoning'
    | '/cases'
    | '/deals'
    | '/import'
    | '/reporty'
    | '/prilezitosti'
    | '/prieskum'
    | '/deal-radar'
    | '/trhova-historia'
    | '/pravny-referent'
    | '/ceny'
    | '/system'
    | '/robots.txt'
    | '/ogc'
    | '/sitemap.xml'
    | '/reporty/$id'
    | '/vypis/$datasetId/$lvNo'
    | '/el/$datasetId/$celok'
    | '/upinfo/$id'
    | '/datasety/$id'
    | '/datasety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapa'
    | '/browser'
    | '/vlastnici'
    | '/zoning'
    | '/cases'
    | '/deals'
    | '/import'
    | '/reporty'
    | '/prilezitosti'
    | '/prieskum'
    | '/deal-radar'
    | '/trhova-historia'
    | '/pravny-referent'
    | '/ceny'
    | '/system'
    | '/robots.txt'
    | '/ogc'
    | '/sitemap.xml'
    | '/reporty/$id'
    | '/vypis/$datasetId/$lvNo'
    | '/el/$datasetId/$celok'
    | '/upinfo/$id'
    | '/datasety/$id'
    | '/datasety'
  id:
    | '__root__'
    | '/'
    | '/mapa'
    | '/browser'
    | '/vlastnici'
    | '/zoning'
    | '/cases'
    | '/deals'
    | '/import'
    | '/reporty'
    | '/prilezitosti'
    | '/prieskum'
    | '/deal-radar'
    | '/trhova-historia'
    | '/pravny-referent'
    | '/ceny'
    | '/system'
    | '/robots.txt'
    | '/ogc'
    | '/sitemap.xml'
    | '/reporty/$id'
    | '/upinfo/$id'
    | '/datasety/$id'
    | '/datasety/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  BrowserRoute: typeof BrowserRoute
  VlastniciRoute: typeof VlastniciRoute
  ZoningRoute: typeof ZoningRoute
  CasesRoute: typeof CasesRoute
  DealsRoute: typeof DealsRoute
  ImportRoute: typeof ImportRoute
  ReportyRoute: typeof ReportyRoute
  PrilezitostiRoute: typeof PrilezitostiRoute
  PrieskumRoute: typeof PrieskumRoute
  DealRadarRoute: typeof DealRadarRoute
  TrhovaHistoriaRoute: typeof TrhovaHistoriaRoute
  PravnyReferentRoute: typeof PravnyReferentRoute
  CenyRoute: typeof CenyRoute
  SystemRoute: typeof SystemRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OgcRoute: typeof OgcRoute
  ReportyIdRoute: typeof ReportyIdRoute
  VypisDatasetIdLvNoRoute: typeof VypisDatasetIdLvNoRoute
  ElDatasetIdCelokRoute: typeof ElDatasetIdCelokRoute
  UpInfoIdRoute: typeof UpInfoIdRoute
  DatasetyIdRoute: typeof DatasetyIdRoute
  DatasetyIndexRoute: typeof DatasetyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogc': {
      id: '/ogc'
      path: '/ogc'
      fullPath: '/ogc'
      preLoaderRoute: typeof OgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prilezitosti': {
      id: '/prilezitosti'
      path: '/prilezitosti'
      fullPath: '/prilezitosti'
      preLoaderRoute: typeof PrilezitostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prieskum': {
      id: '/prieskum'
      path: '/prieskum'
      fullPath: '/prieskum'
      preLoaderRoute: typeof PrieskumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-radar': {
      id: '/deal-radar'
      path: '/deal-radar'
      fullPath: '/deal-radar'
      preLoaderRoute: typeof DealRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trhova-historia': {
      id: '/trhova-historia'
      path: '/trhova-historia'
      fullPath: '/trhova-historia'
      preLoaderRoute: typeof TrhovaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporty': {
      id: '/reporty'
      path: '/reporty'
      fullPath: '/reporty'
      preLoaderRoute: typeof ReportyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoning': {
      id: '/zoning'
      path: '/zoning'
      fullPath: '/zoning'
      preLoaderRoute: typeof ZoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vlastnici': {
      id: '/vlastnici'
      path: '/vlastnici'
      fullPath: '/vlastnici'
      preLoaderRoute: typeof VlastniciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravny-referent': {
      id: '/pravny-referent'
      path: '/pravny-referent'
      fullPath: '/pravny-referent'
      preLoaderRoute: typeof PravnyReferentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporty/$id': {
      id: '/reporty/$id'
      path: '/reporty/$id'
      fullPath: '/reporty/$id'
      preLoaderRoute: typeof ReportyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vypis/$datasetId/$lvNo': {
      id: '/vypis/$datasetId/$lvNo'
      path: '/vypis/$datasetId/$lvNo'
      fullPath: '/vypis/$datasetId/$lvNo'
      preLoaderRoute: typeof VypisDatasetIdLvNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/$datasetId/$celok': {
      id: '/el/$datasetId/$celok'
      path: '/el/$datasetId/$celok'
      fullPath: '/el/$datasetId/$celok'
      preLoaderRoute: typeof ElDatasetIdCelokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upinfo/$id': {
      id: '/upinfo/$id'
      path: '/upinfo/$id'
      fullPath: '/upinfo/$id'
      preLoaderRoute: typeof UpInfoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasety/$id': {
      id: '/datasety/$id'
      path: '/datasety/$id'
      fullPath: '/datasety/$id'
      preLoaderRoute: typeof DatasetyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasety/': {
      id: '/datasety/'
      path: '/datasety'
      fullPath: '/datasety'
      preLoaderRoute: typeof DatasetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  BrowserRoute: BrowserRoute,
  VlastniciRoute: VlastniciRoute,
  ZoningRoute: ZoningRoute,
  CasesRoute: CasesRoute,
  DealsRoute: DealsRoute,
  ImportRoute: ImportRoute,
  ReportyRoute: ReportyRoute,
  PrilezitostiRoute: PrilezitostiRoute,
  PrieskumRoute: PrieskumRoute,
  DealRadarRoute: DealRadarRoute,
  TrhovaHistoriaRoute: TrhovaHistoriaRoute,
  PravnyReferentRoute: PravnyReferentRoute,
  CenyRoute: CenyRoute,
  SystemRoute: SystemRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OgcRoute: OgcRoute,
  ReportyIdRoute: ReportyIdRoute,
  VypisDatasetIdLvNoRoute: VypisDatasetIdLvNoRoute,
  ElDatasetIdCelokRoute: ElDatasetIdCelokRoute,
  UpInfoIdRoute: UpInfoIdRoute,
  DatasetyIdRoute: DatasetyIdRoute,
  DatasetyIndexRoute: DatasetyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
